### ISSUE TITLE
Zoho needs to whitelist our servers

### ISSUE THREAD

**Issue by leonheess** [forwardemail/free-email-forwarding#145]
I didn't change anything but the forwarding doesn't work anymore. I double-checked the DNS-Records but I everything seems to be in order. I'm not self-hosted.

**Comment by niftylettuce** [comment]
The service is working fine and up

**Comment by MiXT4PE** [comment]
Is there anything I can trouble shoot? I tried changing the receiving email but it still doesn't work.

**Comment by MiXT4PE** [comment]
Those are my DNS records: ![image](https://user-images.githubusercontent.com/13834296/60272935-5ca16000-98f5-11e9-883e-93bf1f78fa74.png)

**Comment by niftylettuce** [comment]
I tested from GMX and I received an email, albeit it went to GMX spam

![Screen Shot 2019-06-27 at 9 10 42 AM](https://user-images.githubusercontent.com/523141/60273399-b38a4380-98bb-11e9-85dd-1a1ec5c47f99.png)

**Comment by niftylettuce** [comment]
From your DNS records for `heess-it.de` it does not appear you are forwarding to any GMX email address.  It looks like you are only forwarding all emails to `62hele1bif@hft-stuttgart.de`.  

Upon doing a lookup for `hft-stuttgart.de`, I see that the MX servers are `mx1.belwue.de`.  So you are forwarding emails to this service, and then this service is forwarding emails to GMX?  This is not our problem, this is a problem with your intermediary `hft-stuttgart.de` server.

You must check that the server at `mx1.belwue.de` is properly set up with all requirements (e.g. FQDN, reverse PTR, ...).

**Comment by MiXT4PE** [comment]
That mail server is the one of my university. I switched the destination to check if this was the problem. I now switched it back to my main email address leon@heess.me which is at Zoho but it still doesn't work. Would you maybe look into the logs again? :)

**Comment by niftylettuce** [comment]
You probably need to give it time to propagate OR use the purge cache tool
at https://1.1.1.1/purge-cache/

The university mail server is probably not configured properly.

**Comment by niftylettuce** [comment]
Also, there are ZERO logs, we do not store any logs whatsoever on the
service, so I cannot debug anything.

**Comment by MiXT4PE** [comment]
I see. I temporarily changed it to `forward-email=niftylettuce@gmail.com,leon@heess.me` now so every email at anything@heess-it.de should end up in your mailbox as well. Could you maybe test that for me? If it works I will give up because then it's obviously neither a problem of the service or my DNS configuration.

I will of course remove your email right after and thank you so much for your time :)

**Comment by niftylettuce** [comment]
@MiXT4PE this is odd (my tests):

![Screen Shot 2019-06-27 at 9 42 19 AM](https://user-images.githubusercontent.com/523141/60275746-fea65580-98bf-11e9-9ccf-7bc342b1d088.png)

![Screen Shot 2019-06-27 at 9 42 24 AM](https://user-images.githubusercontent.com/523141/60275756-01a14600-98c0-11e9-915d-57cafca2acdf.png)

**Comment by niftylettuce** [comment]
Also I got your test:

![Screen Shot 2019-06-27 at 9 43 40 AM](https://user-images.githubusercontent.com/523141/60275798-0fef6200-98c0-11e9-9616-4ed85a7ba4fb.png)

**Comment by niftylettuce** [comment]
I will debug this, sec

**Comment by MiXT4PE** [comment]
Thank you so much for looking into this. I'm right here if you need me

**Comment by niftylettuce** [comment]
It appears that that specific Zoho service/server is blocking us, perhaps due to spam or rate limiting.

```sh
Can't send mail - all recipients were rejected: 541 5.4.1 Mail rejected by destination domain
```

It forwards `niftylettuce@gmail.com` successfully, but it does not forward `leon@heess.me` successfully.  The reason why it doesn't say `leon@heess.me` in the screenshot above (https://github.com/niftylettuce/forward-email/issues/145#issuecomment-506376074) is because I mask the forwarding addresses EVEN in error messages for people's security and privacy with the original forwarding address (not the end-recipient).

I'll fix that error message so it's clearer and doesn't get chopped off.

I've reached out to Zoho Support (support@zoho.com) and I suggest perhaps you do the same to see if they can whitelist us.

**Comment by niftylettuce** [comment]
Btw @MiXT4PE 	I just saw this in my spam folder in my Gmail inbox:

![Screen Shot 2019-06-27 at 10 03 18 AM](https://user-images.githubusercontent.com/523141/60277259-d4a26280-98c2-11e9-9fa7-f981068b5964.png)

**Comment by MiXT4PE** [comment]
Yeah that's the one I also got. I wrote an email to Zoho Support and I really hope they whitelist your servers. Thanks for your help I don't have enough knowledge about SMTP and stuff to wrap my head about this stuff.

**Comment by niftylettuce** [comment]
Also just wanted to follow up that the error message is clearer now (you can compare this with the above screenshot; it's joined by a comma):

![Screen Shot 2019-06-27 at 10 06 58 AM](https://user-images.githubusercontent.com/523141/60277530-5f835d00-98c3-11e9-92c8-8b93ee92f69f.png)

**Comment by niftylettuce** [comment]
I'm going to re-open this and change the title to "Zoho and GMX need to whitelist our server"

**Comment by MiXT4PE** [comment]
Do you think the same issue exists with GMX? Didn't you try it yourself and it worked?

Here are the "rules" for send emails to GMX servers again: https://postmaster.gmx.com/en/email-policy - are all of them fulfilled?

**Comment by niftylettuce** [comment]
Good point!  It's only Zoho.

**Comment by MiXT4PE** [comment]
Just for the fun of it I put in a different address by a different provider and tried to send from my zoho-based-address and I got this:

```
From: mailer-daemon@mail.eu.zoho.com
Sent: June 27, 2019 17:17:24
To: leon@heess.me
Subject: Undelivered Mail Returned to Sender

> test@heess-it.de, ERROR_CODE :550, ERROR_CODE :The email you sent 
> has an invalid DKIM signatureâ if you need help please forward this 
> email to support@forwardemail.net or visit https://forwardemail.net
```

Does this help?

**Comment by MiXT4PE** [comment]
That's the answer their support send me:

> On analysis we observed the emails from no-reply@forwardemail.net were rejected on suspicion for Spam by our Antispam Filter. 
> 
> However, we have added the sender domain and email address to your Org Whitelist to ensure those emails are not being rejected any further. 
> 
> However, we see the IP address 178.128.149.101 from which the emails are being sent is currently Blacklisted on multiple DBLs. We request you to contact the sender or technical team for no-reply@forwardemail.net to raise a delist request to have the same removed from the Blacklist. 
> 
> Once done please do monitor the status at your end or you may also let us know so that we can have the IP address added to your Whitelist as well to ensure a seamless email delivery.

**Comment by niftylettuce** [comment]
We are only blacklisted on one list, the SORBS DUHL, which listed us because we have a dynamic IP from Digital Ocean.  I am planning to transition to a fixed/static IP in the near future when I launch V2 of ForwardEmail.net, which should resolve the issue.

**Comment by MiXT4PE** [comment]
After whitelisting no-reply@forwardemail.net within my Zoho-Organisation I now get all emails as I should. However when I am sending from any address using the Zoho mailservers to any other (!) address that uses forward-email I get this:

`ERROR_CODE :550, ERROR_CODE :The email you sent has an invalid DKIM signatureâ if you need help please forward this email to support@forwardemail.net or visit https://forwardemail.net`

I am aware that I can't use forward-email to send from one address to itself but sending from info@heess.me (Zoho) to info@ellenareali.com (using forward-email) shouldn't be an issue, right?

**Comment by niftylettuce** [comment]
Your Zoho has a bad DKIM setup, fix it and you should be okay

**Comment by MiXT4PE** [comment]
Thank you for pointing out that issue on my end. It is now fixed and everything is working perfectly!
