### ISSUE TITLE
reliability via service redundancy advice (question)

### ISSUE THREAD

**Issue by ak2k** [forwardemail/free-email-forwarding#152]
I just learned about and am very exicted about the service!

Do you have any advice/recommendations for steps that might be taken to maximize availability of custom domain forwarding while using forwardemail.net?

In particular, have you given any thought to configurations that would make this service primary (via priority in MX records) and might make [a Mailgun catchall](https://medium.com/issacaption/using-a-custom-domain-in-gmail-for-free-with-mailgun-and-sendgrid-2c54e681f378) or similar secondary, such that in the event forwardemail.net has an interruption in service (e.g. due to a cloudflare or other issue), a custom domain could expect continued deliverability.

Thank you in advance!

**Comment by aaronstuder** [comment]
I don't recommend using a catch all.
https://security.stackexchange.com/questions/129208/what-to-consider-security-wise-when-having-a-mail-catch-all-policy

Second, email servers if unable to deliver an email retry later so there is not a great need for a secondary server, however it would be hard to argue against it as well :)

**Comment by niftylettuce** [comment]
I've set up global load balancing these past few days.
