### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by giggioman00** [forwardemail/free-email-forwarding#155]
I followed the instruction but when I try to send a test email to info@mydomain.com, I receive the Delivery status notification 
This is an automatically generated Delivery Status Notification.      

Delivery to the following recipients was aborted after 12 second(s)
Action: failed
Status: 5.1.1
Diagnostic-Code: smtp;  550 Error for info@mydomain.com of "unable to verify the first certificate"
Last-attempt-Date: Tue, 06 Aug 2019 17:17:07 +0200

Why? I hope I only need to wait more but I see the new mx are already full propagated

**Comment by shaneparsons** [comment]
I'm also now getting this issue, right after changing my receiving mail provider. Similar forwarding setups from Mailgun are able to get through, but not any from this service... Any ideas @niftylettuce?

**Comment by shaneparsons** [comment]
I think this may be related to https://github.com/forwardemail/free-email-forwarding/issues/167.

**Comment by niftylettuce** [comment]
This should be resolved already
