### ISSUE TITLE
Not receiving emails from Apple domains such as icloud.com and mac.com

### ISSUE THREAD

**Issue by jayporter** [forwardemail/free-email-forwarding#160]
Hi there,

First of all, thanks a bunch for offering this very helpful service.

Second, I've recently discovered that emails sent to me from iCloud.com addresses *and* from Mac.com addresses do not go through. No error message or bounce is generated. 

This is true on jay@panga.io and also jay@jayporter.com, both of which now forward to outlook.com, but it was also true when jay@jayporter.com forwarded to gmail.com. (I've been trying different forwarding destinations to track down the problem.)

From the testing I've done, I think the emails are disappearing between forward-email and the sending server (not between forward-email and the destination server). 

Is this a known issue? Is there a known workaround? Am I doing something obviously wrong that causes it?

Thanks for any light you can shed on this.

Best
Jay

**Comment by niftylettuce** [comment]
Hi @jayporter - I will create an iCloud account and further investigate.

**Comment by pyankoff** [comment]
Tried it, message was delivered, but went to spam for some reason (gmail inbox).

**Comment by niftylettuce** [comment]
If you test further and have issues let me know, I just released a ton of updates.

**Comment by farfarsfar** [comment]
This still seems to be an issue, I am not able to receive email sent from iCloud mail accounts.
