### ISSUE TITLE
550 queryTxt ESERVFAIL 

### ISSUE THREAD

**Issue by purebenwoo** [forwardemail/free-email-forwarding#168]
Hi, 

One of the people who email me often is getting the following regularly:

`550 queryTxt ESERVFAIL benwoo.info
`

I also have other SaaS services who tell me they're sending me a validation code that never arrives. My sender included the error messages below

```
Reporting-MTA: dns; googlemail.com
Received-From-MTA: dns; sender@gmail.com
Arrival-Date: Mon, 09 Sep 2019 13:04:54 -0700 (PDT)
X-Original-Message-ID: <7C3B70A6-990F-484F-8C28-4F71F962E0FC@gmail.com>

Final-Recipient: rfc822; email@benwoo.info
Action: failed
Status: 5.0.0
Remote-MTA: dns; mx1.forwardemail.net. (178.128.149.101, the server for the
 domain benwoo.info.)
Diagnostic-Code: smtp; 550 queryTxt ESERVFAIL benwoo.info
Last-Attempt-Date: Mon, 09 Sep 2019 13:05:00 -0700 (PDT)
```

**Am I doing something wrong?**

Thanks in advance ...

ben

**Comment by aaronstuder** [comment]
Looks like it can't read your TXT record.

Here is a similar issue:

https://github.com/niftylettuce/forward-email/issues/7

**Comment by aaronstuder** [comment]
How long ago did you update DNS?

**Comment by aaronstuder** [comment]
> Should this all be on the same line?

No, two lines is correct.

**Comment by purebenwoo** [comment]
weeks ago

---
*Ben Woo*
(212) 724-1188

**Comment by aaronstuder** [comment]
I checked your TXT records, and they look OK to me. I have sent you a test email, did you get it?

**Comment by aaronstuder** [comment]
I didn't get a bounce back, so that's good :)

**Comment by purebenwoo** [comment]
Yes... so I guess it has to do with this one user. Weird!

---
*Ben Woo*
(212) 724-1188

**Comment by aaronstuder** [comment]
Maybe the person sending the email isn't configured correctly?

https://github.com/niftylettuce/forward-email#how-do-you-prevent-spammers-and-ensure-good-email-forwarding-reputation

**Comment by purebenwoo** [comment]
Thanks ... probably!

---
*Ben Woo*
(212) 724-1188

**Comment by kag0** [comment]
I'm having the same issue. I get this error when sending to forwardemail from my gmail address, but when sending to forwardemail from protonmail it goes through fine.

**Comment by niftylettuce** [comment]
If you guys test again and still have issues ping me or email niftylettuce@gmail.com.  Tons of improvements released to the service.
