### ISSUE TITLE
Sender Rewriting Scheme (SRS)

### ISSUE THREAD

**Issue by MrAnnix** [forwardemail/free-email-forwarding#169]
Will Sender Rewriting Scheme (SRS) be inplemented?

**Comment by fbartels** [comment]
Have a look at https://github.com/forwardemail/free-email-forwarding/issues/137#issuecomment-582695721

**Comment by niftylettuce** [comment]
Released as of v6.0.0 and just deployed to all production mail exchange servers.  This should go into effect immediately, and you should no longer have `no-reply@forwardemail.net` nor friendly-from rewrites with a "Reply-To" header being added to your forwarded emails.

As always, thanks for your patience, let me know of any issues, and please consider upgrading to a paid plan or making a donation.

https://forwardemail.net/features
https://forwardemail.net/donate
