### ISSUE TITLE
Add clamav scanning for attachments

### ISSUE THREAD

**Issue by niftylettuce** [forwardemail/free-email-forwarding#17]
https://github.com/srijs/node-clam-engine

**Comment by youdly** [comment]
a third-party signature to consider, [URLHaus](https://urlhaus.abuse.ch/). MalwareWorld (#104) recently include it.

**Comment by niftylettuce** [comment]
Closing for organization purposes in favor of #189 where this will be added very shortly as a release checklist item.  Please follow/subscribe to that issue for further updates.
