### ISSUE TITLE
Get target via http-request

### ISSUE THREAD

**Issue by muellerlukas** [forwardemail/free-email-forwarding#171]
Idea:
Also allow domain owners to tell the target a web request.

Idea how to implement:
Set a TXT-Record like "forward-email=https". When this is detected the software sends a request to "DOMAIN/.well-known/forward-email?email=MAILADDRESS" where DOMAIN is the domain the mail is sent to and MAILADRESS the mailadress the mail is sent to.
The server returns with the target mail adress. Unencrypted or encrypted (when #6 #3 is done) and maybe a caching time.
The server then sends the mail to this address and caches the target for the given caching time. When not given: I think a default caching time with the value of the DNS-Record would be ok.

Reason:
Some providers dont offer a API to set your DNS-Records. With this feature you can set the record one time and then manage your forwardings via database or something.

**Comment by tracker1** [comment]
That's actually an awesome idea in general... would suggest the ability to combine with a :port for smtp. such as a response of `USER@HOST:PORT` for the forwarded address.

**Comment by niftylettuce** [comment]
I'm going to close this as I believe this is resolved through the new `forward-email-site-verification` TXT record setup.  Fully open source, should you choose to host it yourself.  See our website for how it works.
