### ISSUE TITLE
Cannot receive verification email (in Chinese) to add Microsoft account alias

### ISSUE THREAD

**Issue by jingyu9575** [forwardemail/free-email-forwarding#172]
I've set up `my.domain.com` to forward to `me@outlook.com`, and now trying to add `name@my.domain.com` as an alias to my Microsoft account, so that I can send email from this address. 

However, the verification email (in Chinese) can not be forwarded. It only works after I changed the account's language to English, so the email is sent in English.

This is the email in Chinese with this problem, received from another personal email. It is equivalent to the English text below.

> From: Microsoft 帐户团队 <account-security-noreply@accountprotection.microsoft.com> 
> Subject: 确认你的 Microsoft 帐户的电子邮件地址
> 
> 你好!
> 你似乎已将一个电子邮件地址添加为 Microsoft 帐户别名。
> \- 添加了 my.domain.com
> 注意: 如果尚未登录该帐户，你需要使用已验证的电子邮件地址登录。
> 如果你已将此电子邮件地址添加为别名，请使用下面的链接进行验证:
> https://account.live.com/Aliases/Verify?aliasname=name%40my.domain.com&aliastype=Email&otc=...&mn=me%40outlook.com&cxt=Default
> 如果你没有提出此请求，请使用下面的链接取消:
> https://account.live.com/Aliases/Remove?aliasname=name%40my.domain.com&aliastype=Email&otc=...&mn=me%40outlook.com&cxt=Default
> 
> 谢谢!
> Microsoft 帐户团队

This is the email in English that works:

> From: Microsoft account team <account-security-noreply@accountprotection.microsoft.com> 
> Subject: Confirm your email address for your Microsoft account
> 
> Hi,
> It looks like you added an email address as a Microsoft account alias.
> \- my.domain.com Added
> NOTE: If you're not already logged in to this account, you will need to log in using an email address that has already been verified.
> If you added this email address as an alias, use this link to verify:
> https://account.live.com/Aliases/Verify?aliasname=name%40my.domain.com&aliastype=Email&otc=...&mn=me%40outlook.com&cxt=Default
> If you didn't make this request, use this link to cancel:
> https://account.live.com/Aliases/Remove?aliasname=name%40my.domain.com&aliastype=Email&otc=...&mn=me%40outlook.com&cxt=Default
> 
> Thanks,
> The Microsoft account team

I think the Chinese email cannot pass the span filter in forwardemail. Could you have a check on the filter, or whitelist accountprotection.microsoft.com ?

Thank you.

**Comment by tracker1** [comment]
Just a thought... have a whitelist of say the top 50 service providers, and if the forward and reverse DNS for connecting IP match to that tld bypass?  Not sure if this is a great idea or not though... I literally stopped self-hosting SMTP because spam rules became a byzantine nightmare to deal with.

**Comment by niftylettuce** [comment]
Can you test again?  I've done a ton of improvements to the service.

**Comment by jingyu9575** [comment]
I just tested it but it still does not work. Additionally, I'm no longer able to send to the forwarded address from Microsoft Live mail. 

> mx1.forwardemail.net
> Remote Server returned '550 5.0.350 Remote server returned an error -> 550 Your email contained an invalid DKIM signature. For more information visit https://en.wikipedia.org/wiki/DomainKeys_Identified_Mail. You can also reach out to us for help analyzing this issue. - if you need help please forward this email to support@forwardemail.net or visit https://forwardemail.net'

[OriginalHeaders.txt](https://github.com/forwardemail/free-email-forwarding/files/3931126/OriginalHeaders.txt)

I can send from another email provider 126.com and received the forwarded email.

**Comment by niftylettuce** [comment]
Can you send me the full original raw email instead of just the headers?  Feel free to email to niftylettuce@gmail.com.  This will help greatly.

**Comment by jingyu9575** [comment]
[emails.zip](https://github.com/forwardemail/free-email-forwarding/files/3933849/emails.zip)

I've attached the email I sent (sent.eml), and the error message from Microsoft (error.eml).
The Chinese in error.eml basically says: mx1.forwardemail.net rejects my email to the address, only email provider can fix it, and the technical data is the headers I attached in the last message.

**Comment by niftylettuce** [comment]
This issue should now be resolved.  Please try again and let me know if you still have issues!!!

**Comment by jingyu9575** [comment]
Yes the issue about receiving from outlook.com has been resolved. Thank you very much!

---

However, the original issue of Chinese verification email still happens here. I'm unable to receive it if the language is Chinese, and there is no error messages. 

The problematic email, when sent to another host 126.com, is this: 
[Chinese-verification.zip](https://github.com/forwardemail/free-email-forwarding/files/3935001/Chinese-verification.zip)

and this is the English version which has no problem:
[English-verification.zip](https://github.com/forwardemail/free-email-forwarding/files/3935002/English-verification.zip)
