### ISSUE TITLE
Self-Hosted -- Need Some Clarification

### ISSUE THREAD

**Issue by kevdogg** [forwardemail/free-email-forwarding#173]
Although I know this usually isn't the forum for this question, I thought I'd ask.

I'm trying to test the Self Hosted solution.  I spun up Ubuntu within a VM and installed all the required packages.  I guess my question is -- now what???  Is there a service I need to start to get this running?

**Comment by tracker1** [comment]
Best bet may be to look into the Dockerfile suggested as part of #111, you'll need to setup a systemd/init script for the service itself in order to have it start.  You'll need inbound port 25 available as well, for the mail forwarding itself to work.

**Comment by tracker1** [comment]
And by look into the Dockerfile, I don't mean use Docker, which you can absolutely do, I only mean that a Dockerfile is a set of instructions on how to build/run something, generally speaking.

**Comment by planetahuevo** [comment]
Hi, 
I would like to try the self hosted solution but I cannot find any documentation about it. 
Can you point me to any links? 

Thanks

**Comment by niftylettuce** [comment]
https://github.com/forwardemail/free-email-forwarding/blob/master/SELF-HOSTING.md#self-hosting

https://github.com/forwardemail/free-email-forwarding/pull/205

**Comment by planetahuevo** [comment]
Thanks! Maybe add that to the FAQ? https://forwardemail.net/en/faq#how-fast-is-this-service :)
