### ISSUE TITLE
Is there a way to set several single email forwarding and set a global catch-all forward to catch all of the 

### ISSUE THREAD

**Issue by jiakeke** [forwardemail/free-email-forwarding#176]
Is there a way to set several single email forwarding and set a global catch-all forward to catch all of the others email which not set to forward?

for example, I set my domail name my.com
single settting:
 forward-email=hello:hello-my@gmail.com
 forward-email=test:test-my@gmail.com
 forward-email=support:support-my@gmail.com

global settting:
 forward-email=others-my@gmail.com

If I send a email to hello@my.com it should be forward to hello-my@gmail.com,
and if I send to another name which is not setting then it will goes to others-my@gmail.com

I have tried that, but looks all the emails will be forward to the global email, if it is set.

Could that be supported?

btw, forwardemail is a great job.
thanks a lot!

Gary

**Comment by allanlaal** [comment]
This has been implemented: https://forwardemail.net/#/?id=can-i-have-multiple-global-catch-all-recipients

**Comment by niftylettuce** [comment]
Yes this should already work as intended.  If there is no specific forwarding address and global catch-all's are configured, then it will use those.
