### ISSUE TITLE
SPF Fails for forwardemail.net

### ISSUE THREAD

**Issue by ParveenBhadooOfficial** [forwardemail/free-email-forwarding#178]
even when it shows the send domain as forwardemail.net the spf fails. why?

![spf](https://user-images.githubusercontent.com/35890959/67145168-b9f26000-f29c-11e9-8446-b305b77f4344.PNG)

**Comment by tracker1** [comment]
Did you add an SPF record for forwardemail.net to send mail for YOURDOMAIN.COM?  You should just add the MX for forwardemail.net or the A record you're pointing to.

**Comment by ParveenBhadooOfficial** [comment]
So does SPF Fails because the sender doesn't have a spf record for forwardmail.net like if we send a mail from gmail?

DMARC and DKIM are passing so nothing to worry about?
