### ISSUE TITLE
Email Forwarding Limits

### ISSUE THREAD

**Issue by ParveenBhadooOfficial** [forwardemail/free-email-forwarding#179]
Is it possible to receive more than 200 emails per hour. or what are these limitations. are they per domain (mail.iii.ind.in, test.iii.ind.in) or applies on the entire domain (iii.ind.in)?

I use GSuite but there is a problem when i use Wildcard with GSuite, as i have to add MX Records for every sub-domain. while forwardmail.net fixed that problem.

**Comment by ParveenBhadooOfficial** [comment]
I sent 211 emails from same address to different sub domains of same domain and they delivered within 10 minutes. Emails were sent via amazonses.com . Once clarify, what are the limits on?

**Comment by DaWe35** [comment]
Hello!
As you can see in the code (index.js), the limiter checks the recipient address, not only the domain/subdomain. So you can send 200 email to every address per hour, doesn't matter, where you send.

    const { address, addresses } = recipient;
...

    validateRateLimit(email) {
        ...
    }

Can somebody confirm this?

**Comment by niftylettuce** [comment]
Closing for organization purposes in favor of #189 where this will be added very shortly as a release checklist item.  Please follow/subscribe to that issue for further updates.
