### ISSUE TITLE
Multiple MX?

### ISSUE THREAD

**Issue by shaneparsons** [forwardemail/free-email-forwarding#180]
[This part of the documentation](https://github.com/forwardemail/free-email-forwarding#can-i-just-use-this-mail-forwarding-service-as-a-fallback-or-fallover-mx-server) claims that it's okay to use these MX records alongside an external service's MX records, as long as the priority on these ones is a higher number.

In my particular situation I don't wish to use this service as a fallback, but as forwarding for an email address that doesn't exist on my Microsoft 365 account.

e.g.
john@example.com (licensed)
smith@example.com (licensed)
support@example.com (unlicensed / wish to forward)

Will this work for my situation, or is it meant for fallback purposes only?

**Comment by shaneparsons** [comment]
@niftylettuce can you shine some light on this?

**Comment by aaronstuder** [comment]
Can you use a sub domain? That would be easier for sure.

**Comment by shaneparsons** [comment]
@aaronstuder in this particular situation it wouldn't be ideal.

**Comment by aaronstuder** [comment]
Sadly I can’t think of a way to do it, because i think the first server will reject it, and it will never try the second server (I cloud be wrong)

**Comment by aaronstuder** [comment]
What you could do it setup a relay in front of exchange, and have some mail forwarded and some forwarded on.

**Comment by aaronstuder** [comment]
If you have a spam filter in front of exchange it might allow this

**Comment by aaronstuder** [comment]
How are you going to handle sending emails from those accounts?

**Comment by shaneparsons** [comment]
The unlicensed email (e.g. support@example.com) would just be a way for the client (example.com) customers / notifications to reach me, the developer, so I'm not concerned about sending from the account... Which is why I was hoping it'd be as simple as adding an additional MX.

Thanks though, I'll look into the relay stuff and see what I can find.

**Comment by shaneparsons** [comment]
Ah okay, I was actually able to set this up in MS directly using something they call a distribution list. I'll close this issue for the time being, although I would still be interested to know if something like this is possible, in the case that an email provider doesn't offer this option.
