### ISSUE TITLE
Can not proceed "send mail as using gmail" section

### ISSUE THREAD

**Issue by codemilli** [forwardemail/free-email-forwarding#181]
When I visit https://myaccount.google.com/apppasswords , there is no any prompt described at https://forwardemail.net/#/?id=send-mail-as-using-gmail

**Comment by niftylettuce** [comment]
You have to enable two factor authentication

**Comment by niftylettuce** [comment]
I updated the docs to reflect this, thank you

**Comment by codemilli** [comment]
I followed the step so I skip step 2,3 and go to 4 directly but was stuck in step 11 which is `When prompted for Password, paste from your clipboard the password you generated in step 2 above` because I skipped step 2. 

Many thanks !
