### ISSUE TITLE
Question: Can this help me send emails from a dynamic IP?

### ISSUE THREAD

**Issue by DumboJetEngine** [forwardemail/free-email-forwarding#182]
I was experimenting recently on setting up my very own mail server.
I am generally new to the world of mail and I certainly have a lot to learn.
I have a free domain on a dynamic IP provider, in the form of `mydomain.****.***`.
Once I thought I was done setting up my server, and I tested that I could indeed receive emails, I discovered that I could not send any emails, because other mail servers would block me, since I am on a dynamic IP and I have no SPF records. Or, at least, that's my impression about the reason...

Can your service help me solve this issue by forwarding only my outgoing mail? Or the fact that I am on a dynamic IP, with no SPF records, will still be a problem for trusting me?
There is a section in your instructions called `Can I forward my emails from a well-known provider`, but my mail server does not fall under this category, so I am not sure what is the answer to my question. Also, there was no mention about dynamic IPs on your instructions, so once again I was left wondering.

Suggestion:
You mention that your mail forwarder provides more security than others. I think it would be nice to make a list of things that are more secure on it, for people like me to understand some things. I guess one thing is the fact that you don't keep data or logs. Generally, I found that reading the instructions for using your service made me learn some things (e.g. some DNS-related options), so this might help a lot of people to understand better how things work.

**UPDATE:**
I have just noticed a mention of DKIM in your documentation and started looking into it. I had no idea what it was so far and that it ever existed. I am thinking to try it out (at least, if it possible to do so without spending money) and see if it helps me send my email from my dynamic IP and without using 3rd party services. I would be great if this worked...

**UPDATE 2:**
After reading some extra information online, I believe the problem is in the PTR records. I have found one dynamic IP provider that supports free PTR records (dynu), but not sure if I can update them dynamically. Most likely, I won't be able to use a PTR record with dynamic IP, since my IP is already linked to an ISP hostname. However, `MX Tools` reports no problem at `SMTP Reverse DNS Mismatch` when testing my mail server. So, most likely it is not the PTR the problem?

**Comment by notpushkin** [comment]
If this helps, I've successfully sent (DKIM-signed and SPF-verified) emails to _some_ email providers right from my home ISP. Notably though, Gmail and Zoho don't accept emails from such IP addresses, and chances are you're on such a network too (are you?). If so, you'll likely need to host an SMTP server somewhere, or use a third-party one (like I did). You'll still be able to receive emails through ForwardEmail just fine.

**Comment by DumboJetEngine** [comment]
Yes, that is my understand as well.
Most email providers do not accept emails from SMTP servers on dynamic IPs, in order to avoid spam.
So, the only options seem to be:

- using a static IP
- hosting an SMTP server on a hosting environment
- hosting an SMTP relay on a hosting environment
- using a 3rd party SMTP relay

I have gone with the last option for now (I use MailJet as a relay), but I was hoping I could find an alternative. The benefit of privacy goes away when using 3rd parties.

**Comment by niftylettuce** [comment]
It is on my list to make a relay in the future on this service

**Comment by DumboJetEngine** [comment]
That would be nice. 👍

**Comment by tracker1** [comment]
If you're under 100 emails a day, you can use sendgrid for free, this is what I use for an outbound relay since it's less hassle with running my own outbound server.

**Comment by niftylettuce** [comment]
Sendgrid is not HIPAA compliant nor privacy focused just fyi

**Comment by notpushkin** [comment]
Privacy-wise, I would still prefer SendGrid to Gmail or something, however :) (Not sure about HIPAA or anything)

**Comment by niftylettuce** [comment]
Closing for organization purposes in favor of #189 where this will be added very shortly as a release checklist item.  Please follow/subscribe to that issue for further updates.
