### ISSUE TITLE
Issue with recieving email from certain senders

### ISSUE THREAD

**Issue by ogiwankanobe** [forwardemail/free-email-forwarding#183]
Hello, 

We're having issues receiving emails from certain senders (they happen to be .edu and .org, although we've received emails from others without issues) ....are you able to help tell us why? 

Thanks!

**Comment by niftylettuce** [comment]
If they are receiving a bounce back message please pass it along to support@forwardemail.net for investigation.  I cannot help without having more information as to the contents of the message and the sender's full from address.

**Comment by elsiehupp** [comment]
I created unique email addresses for my accounts with both Autodesk and Adobe, but the verification emails do not seem to have been delivered. When I send emails to myself at those email addresses, my test emails do get delivered. The missing emails do not appear in my spam folder. Some email senders do work, but not these two. Might this be an issue with one or another of forward-email's anti-spam features?

(FYI my domain is elsiehupp.com. The emails getting bounced are from automated systems, so there's no way for me to see them.)

**Comment by niftylettuce** [comment]
I have confirmed Amazon.com and Adobe.com are not passing DKIM tests.  I will fix immediately after investigation and report back to you.

**Comment by niftylettuce** [comment]
See <https://github.com/forwardemail/free-email-forwarding/issues/192#issuecomment-565362550> for updates.  I am implementing a fix and deploying it shortly!!!  Discovered the bug, it was with a core Python v2.x DNS lookup.  Python v3 will fix issue.
