### ISSUE TITLE
Send Mail As Using Gmail – Authentication failed (534-5.7.14)

### ISSUE THREAD

**Issue by piotr-dobrogost** [forwardemail/free-email-forwarding#185]
When following https://forwardemail.net/#/?id=send-mail-as-using-gmail (**not using two-factor authentication**) in step

> 13. Click `Add Account` to proceed

I was getting `Authentication failed. Please check your username/password. [Server response: 534-5.7.14 (...)` error.

Every time I tried to add account I got email from Google titled "Critical security alert" with the following message:

> Sign-in attempt was blocked
> Someone just used your password to try to sign in to your account. Google blocked them, but you should check what happened.

Going to https://www.google.com/accounts/DisplayUnlockCaptcha (as suggested at https://support.google.com/mail/answer/7126229 Gmail support page) fixed the issue.

**Comment by michaelotto** [comment]
Thanks, that was helpful. Worked for me too.

**Comment by MoazAlkharfan** [comment]
I think this is good to be added into the guide.

**Comment by niftylettuce** [comment]
Closing for organization purposes in favor of #189 where this will be added very shortly as a release checklist item.  Please follow/subscribe to that issue for further updates.
