### ISSUE TITLE
550 Hostname/IP doesn't match certificate's altnames forwarding to 163.com

### ISSUE THREAD

**Issue by kshepherd2013** [forwardemail/free-email-forwarding#186]
I have several forward-emails set up in TXT records in DNS.  All the gmail.com ones work perfectly, but one to 163.com fails.
Is there anything I can do to the configuration to fix this?

Here is the DNS entry: 
forward-email=zs.lin:xiaolinzs@163.com

Here is the error from the SMTP server:
Action: failed
Status: 5.0.0
Remote-MTA: dns; mx1.forwardemail.net. (178.128.149.101, the server for the
 domain shangrila-gourmet.com.)
Diagnostic-Code: smtp; 550 Message was sent successfully to ted.marr@shangrila-gourmet.com and darius.wong@shangrila-gourmet.com, Error for zs.lin@shangrila-gourmet.com of "Hostname/IP doesn't match certificate's altnames: "Host: 163mx02.mxmail.netease.com. is not in the cert's altnames: DNS:*.163.com, DNS:163.com""
Last-Attempt-Date: Sun, 24 Nov 2019 02:38:23 -0800 (PST)

I am happy to provide more information, run tests, etc.

**Comment by Magneticdud** [comment]
I have the same problem with "telecom italia business" emails 

> "Hostname/IP does not match certificate's altnames: Host: mx.impresasemplice.it. is not in the cert's altnames: DNS:mx1.mse.messcube.it, DNS:out1.mse.messcube.it, DNS:out2.mse.messcube.it, DNS:out3.mse.messcube.it, DNS:out4.mse.messcube.it, DNS:out5.mse.messcube.it, DNS:out6.mse.messcube.it"

**Comment by niftylettuce** [comment]
This is on your end.  Not ours.  It is clear that whoever set up the certificates for those domains did so incorrectly.  You need to reach out to the IT departments of those organizations, not me.
