### ISSUE TITLE
Forwarding TO disposable e-mail

### ISSUE THREAD

**Issue by Bestulo** [forwardemail/free-email-forwarding#187]
I know that forwarding from disposable e-mails can get ForwardEmail servers blacklisted. However, is forwarding TO disposable e-mail addresses any risk at all? I tried using burnermail.com in order to tackle #6 temporarily while the privacy update came out, but test e-mails got rejected by ForwardEmail servers, citing the no-disposable-emails policy. If forwarding TO disposable emails poses no risk, I would suggest enabling that in order to promote user safety and privacy (unless you believe that it's going to add unnecessary load to your server due to their temporary nature).

**Comment by niftylettuce** [comment]
This has been released, deployed, and should work now!

Let me know if you have any issues or other feature requests 🎉 👍 

Released in [v3.1.0](https://github.com/forwardemail/free-email-forwarding/releases/tag/v3.2.0).
