### ISSUE TITLE
Cannot receive emails from Apple services

### ISSUE THREAD

**Issue by yar1vn** [forwardemail/free-email-forwarding#190]
Tried signing up for an Apple account with my custom domain email and never received a confirmation email. 
Also tried adding it as an alias to my existing iCloud email account and haven’t received a confirmation as well. 

I don’t use gmail as an email provider, it’s possible this services is tailored for gmail only?
Thanks!

**Comment by niftylettuce** [comment]
No it should work fine with Apple.  Can you email me at niftylettuce@gmail.com with your apple mail user/domain?

**Comment by Lambdac0re** [comment]
Not sure if this is related but I am not receiving emails from klarna.com and flixbus.de, everything else seems to work fine (I use it daily).

**Comment by yar1vn** [comment]
I just switched to Mailgun but I’m happy to switch back for testing if that’s helpful.

**Comment by niftylettuce** [comment]
This should be resolved now by the way.

**Comment by Lambdac0re** [comment]
@yar1vn thx for the tip, also switching the mx server in the meantime

**Comment by niftylettuce** [comment]
There is no need for you to use other services - the issue is fixed 😄 
cc @Lambdac0re @yar1vn

**Comment by Lambdac0re** [comment]
@niftylettuce What was the issue anyway?

**Comment by niftylettuce** [comment]
https://github.com/niftylettuce/python-spfcheck2/commit/40515c6ee830e8e923ec105e1312a49febb94328#diff-168726dbe96b3ce427e7fedce31bb0bcL27 vs. https://github.com/niftylettuce/python-spfcheck2/commit/6dfaaedbad2cbea78b06c7132eb71d8edbdd307e#diff-168726dbe96b3ce427e7fedce31bb0bcR27

There was a typo - that was the issue 🤦‍♂
