### ISSUE TITLE
550: missing required DNS MX records of mx1.forwardemail.net, mx2.forwardemail.net

### ISSUE THREAD

**Issue by plweil** [forwardemail/free-email-forwarding#194]
I set this up almost 12 hours ago. Running Dig on my domain shows that the DNS config is in order (I think?):

`dig +short MX mydomain.com`
`10 mx1.fowardemail.net.`
`20 mx2.forwardemail.net.`

Same for the TXT records

Yet I still can't email to this domain. Delivery keep failing with 

`550: missing required DNS MX records of mx1.forwardemail.net, mx2.forwardemail.net`

I would really like to get this going. Any idea what the issue might be?

Thank you.

**Comment by niftylettuce** [comment]
Have you used the purge cache tool?

https://1.1.1.1/purge-cache/

Also, what service are you sending email through?

Feel free to email me at support@forwardemail.net (I think you may have already?).

Sorry been out the day.

**Comment by plweil** [comment]
I’ve purged the cache with the purge cache tool twice. Emails are still being rejected with the same error — I just another one out this morning.

I am sending mail through the smtp service at the University of WIsconsin-Madison, which uses Office 365/Exchange, although I tried sending one through gmail, and the same thing happened.

**Comment by devkmsg** [comment]
Check the spelling of your MX records. The mx1 record in your dig results is misspelled.

**Comment by niftylettuce** [comment]
@devkmsg 	nice find! @plweil 	see his comment!

**Comment by plweil** [comment]
Sometimes you can stare at something for 20 minutes and not see what someone else can find in 5 seconds. Very humbling. Thank you.
