### ISSUE TITLE
How is this related to https://github.com/forwardemail/forwardemail.net?

### ISSUE THREAD

**Issue by pke** [forwardemail/free-email-forwarding#195]
I wonder how the two projects are related. Is this the "old" project and https://github.com/forwardemail/forwardemail.net the new one?

**Comment by niftylettuce** [comment]
This is the service that runs the mx servers, the new one is the web server and front-end that manages everything (more to come soon).

**Comment by niftylettuce** [comment]
I could probably rename this to smtp-server or something, what do you think?

**Comment by pke** [comment]
hmmm ok. Can just leave the name for now just put some hint of what it does in the repos description?

**Comment by niftylettuce** [comment]
Done

<img width="675" alt="Screen Shot 2020-01-15 at 5 30 07 PM" src="https://user-images.githubusercontent.com/523141/72480324-b21f5a80-37bc-11ea-96b7-22f0cd4f6f92.png">
<img width="678" alt="Screen Shot 2020-01-15 at 5 30 00 PM" src="https://user-images.githubusercontent.com/523141/72480325-b21f5a80-37bc-11ea-9d7b-53a20559dea8.png">
