### ISSUE TITLE
Cannot signin through GitHub

### ISSUE THREAD

**Issue by AdrienPoupa** [forwardemail/free-email-forwarding#196]
I am getting

```
Cannot read property '0' of undefined
```

**Comment by niftylettuce** [comment]
Yeah someone else had this too.  It's a core bug in `passport-github` and `passport-github2`.  I still haven't figure it out yet though.

**Comment by niftylettuce** [comment]
OK I see what's wrong, just need to patch it, need a few

**Comment by AdrienPoupa** [comment]
No worries, this is an awesome tool thanks a ton for maintaining it!

**Comment by niftylettuce** [comment]
@AdrienPoupa 	could you try again and let me know if it works?  I believe I've fixed it.  Let me know either way please, and thank you!

https://forwardemail.net/auth/github

**Comment by AdrienPoupa** [comment]
Yes, it is working. Thanks!
