### ISSUE TITLE
MX Records not verifying (Cloudflare)

### ISSUE THREAD

**Issue by Yogsther** [forwardemail/free-email-forwarding#197]
I have purged the cache multible times, and via lookup's the MX records look correct. 
However, forwardemail.net is not verifying the MX records. (TXT records are working)

![image](https://user-images.githubusercontent.com/6502251/72887463-06ba5c80-3d0c-11ea-8b5e-8df2f8839d34.png)

http://mxlookup.online-domain-tools.com/link/1d27aa8gw9K3bsMlvf/

**Comment by niftylettuce** [comment]
I just logged in as you and it seems to work OK:

![Screen Shot 2020-01-22 at 5 10 25 AM](https://user-images.githubusercontent.com/523141/72889547-8842c800-3cd5-11ea-910c-654c044bd0b5.png)

Refresh the page and it should show as verified.

**Comment by Yogsther** [comment]
Thank you, guessing the DNS just had to update on your servers.

**Comment by tracker1** [comment]
Yogsther a *LOT* of DNS servers and forwarders will cache entries for an hour or more, depending on internals and a previous record and its' timeout value.  So generally best to let it be and check again in 15m for things like this.
