### ISSUE TITLE
Why is ForwardEmail's SPF record required?

### ISSUE THREAD

**Issue by notpushkin** [forwardemail/free-email-forwarding#198]
I'm wondering why do we need to add `v=spf1 a mx include:spf.forwardemail.net -all` to use it? Isn't SPF about _sending_ email from a particular domain (i. e. “only allow IPs x.x.x.x and x.x.y.y to send emails from @example.com”)? Or does it have something to do with sending via Gmail? Sorry for bothering but I'm not sure how it works and genuinely curious!

P. S. Thank you so much for such a wonderful service!

**Comment by tracker1** [comment]
My guess is that the service is adding an X-Forwarded-For header, or something similar in order to deliver the message and this will trigger a request for domain validation similar to working with sendgrid or mailgun.

**Comment by devkmsg** [comment]
SPF is used by the receiver to ensure the sender is trustworthy.  For incoming email the sender will change to forwardemail.net as it’s forwarded, that’s why we need the spf record.  Check out this for more detailed info: https://www.dmarcanalyzer.com/spf/

**Comment by notpushkin** [comment]
@devkmsg But I mean, it doesn't send anything from my own domain — only from `noreply@forwardemail.net`, which obviously has to have its own SPF record.
@tracker1 Probably it is something like that – I'll look into it, thanks!

**Comment by niftylettuce** [comment]
In order to pass SPF check, you need to include our SPF record.

**Comment by notpushkin** [comment]
@niftylettuce Sorry, but I still don't get it :')

If I'm not mistaken (am I?), SPF check is performed only when you're sending email, which ForwardEmail doesn't perform (Gmail does, [if you use it](https://forwardemail.net/en/faq#how-to-send-mail-as-using-gmail)). If I'm using my own SMTP server, is it safe to omit ForwardEmail's SPF records or are they used for something else? Thank you!

**Comment by niftylettuce** [comment]
ForwardEmail does send email, it's a proxy/middle man, so you need it.

**Comment by notpushkin** [comment]
It does indeed send email _to me_, but not _from my address_. SPF is all about checking sender address, isn't it? So it should in fact point to your SMTP server's addresses (Gmail or otherwise).

Sorry if I'm bothering you too much, I'm just trying to understand.

**Comment by tracker1** [comment]
@notpushkin haven't looked in a while, but iirc, it does send from your domain, but there's a reply-to header to the original sender.
