### ISSUE TITLE
This doesn't bode well.

### ISSUE THREAD

**Issue by JayHoltslander** [forwardemail/free-email-forwarding#201]
![](https://pbs.twimg.com/media/EPkccnYU4AAhqQx?format=jpg&name=large)

**Comment by niftylettuce** [comment]
Looks like a misconfiguration on your side? Our SPF has -all.

```
;; ANSWER SECTION:
forwardemail.net. 262 IN TXT "v=spf1 a mx include:spf.forwardemail.net include:_spf.google.com -all"
```

Also, if you file another issue with a title like that I will ban you.





On January 31, 2020 12:29:22 AM UTC, Jay Holtslander <notifications@github.com> wrote:
>![](https://pbs.twimg.com/media/EPkccnYU4AAhqQx?format=jpg&name=large)
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/forwardemail/free-email-forwarding/issues/201

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by niftylettuce** [comment]
Closing unless you can provide more insight / sender / raw email.  Email support@forwardemail.net with this.
