### ISSUE TITLE
Should this work with UnoEuro hosted domains?

### ISSUE THREAD

**Issue by KristianMedK** [forwardemail/free-email-forwarding#202]
I've tried to setup email forwarding using the guide here https://forwardemail.net/en/faq#how-do-i-get-started-and-set-up-email-forwarding

However my domain keeps displaying as not verified, and when i click verify i get the following message: 

"test@mydomain.dk domain of mydomain.dk has a blank "forward-email" TXT record mydomain.dk is missing required DNS MX records of mx1.forwardemail.net and mx2.forwardemail.net
OK"

Even though these records are setup thorugh my provider, and testing with https://intodns.com/ the mx records specifically looks right to me:

"
Your MX records that were reported by your nameservers are:

10   mx1.forwardemail.net   178.62.29.206 138.197.213.185 (no glue)
20   mx2.forwardemail.net   104.248.224.170 (no glue)
"

Does this solution only work with the providers mentioned in the FAQ, or could i be missing something else ?

for completeness sake, the other txt records i've setup have the following values:
v=spf1 a mx include:spf.forwardemail.net -all
forward-email=support@myotherdomain.dk

**Comment by niftylettuce** [comment]
DNS takes a while to propagate, you can try the purge cache tool in our guide or just wait a bit before trying again.

**Comment by KristianMedK** [comment]
I tried the purge cache tool for mx and txt records. 

I'll let it be for a few hours and see if it picks up.

**Comment by KristianMedK** [comment]
It works now, patience was key.
