### ISSUE TITLE
Question: Does the new MariaDB license prohibit self-hosting for personal use?

### ISSUE THREAD

**Issue by astrob0t** [forwardemail/free-email-forwarding#204]
Hi,
I had been self-hosting this for my personal use but v5.0.0 introduced a new MariaDB Business Source license and I also can't find the self-hosting instructions anymore in the FAQ/README.

* Does that mean I am stuck with a version < v5.0.0 if I plan to stick to self hosting?
* Will the new tiered plans from the Forwardemail.net service be available for self-hosting via a licensing system?
* Has Forwardemail.net completely transitioned to an open sourced SaaS offering?

**Comment by niftylettuce** [comment]
1. No

2. See <https://github.com/forwardemail/free-email-forwarding/blob/master/LICENSE#L9-L16> and in particular:

```txt
Additional Use Grant: You may use the Licensed Work, provided that you do not
                      use the Licensed Work for an Email Service.

                      An "Email Service" is a commercial offering that allows
                      third parties (other than your employees and contractors)
                      to access the functionality of the Licensed Work so that
                      such third parties directly benefit from the email
                      forwarding (or other) features of the Licensed Work.
```

You can use it for self-hosting, but not for an a commercial email service as described.

3. This has had way more traction than I could ever imagine so I am trying to ensure it is stable and is reliable - so yes.
