### ISSUE TITLE
Reject disabled aliases

### ISSUE THREAD

**Issue by fbartels** [forwardemail/free-email-forwarding#206]
Hi,

the [FAQ says](https://forwardemail.net/en/faq#can-i-disable-specific-aliases) that email for disabled aliases are discarded internally:

> "the emails themselves will go nowhere; to a blackhole."

a but further down in the section that deals with [spam protection](https://forwardemail.net/en/faq#how-do-you-prevent-spammers-and-ensure-good-email-forwarding-reputation) its explained that mail marked as spam by spamc is directly rejected.

I think it would be nice if disabled aliases are rejected as well as afaik from a legal standpoint you have received all email that you have not rejected.

PS: in that chapter you also write that you block senders from disposable email domains. are these rejected as well or are they discarded?

**Comment by niftylettuce** [comment]
Disabled aliases will not be rejected until they are deleted as aliases completely.  The reason being is because a common reason for disabling an address is to preserve the service it is signed up for but to prevent the spam associated.

**Comment by niftylettuce** [comment]
We are allowing all disposable emails with the v7.0.0 release soon.  I will comment again here once this is LIVE.

**Comment by niftylettuce** [comment]
Deployed!
