### ISSUE TITLE
API to programatically CRUD alias?

### ISSUE THREAD

**Issue by AquiGorka** [forwardemail/free-email-forwarding#208]
I was not able to find the documentation to programmatically create/delete aliases, can you point me in the right direction?

**Comment by niftylettuce** [comment]
I'm sorry - I had to take care of some stuff, I will be following up ASAP. Hopefully the end of the week. Tons of updates and features (like these) coming your way.

Thank you all for your patience 🙏

**Comment by niftylettuce** [comment]
Closing for organization purposes in favor of #189 where this will be added very shortly as a release checklist item.  Please follow/subscribe to that issue for further updates.

**Comment by niftylettuce** [comment]
API is released, see https://forwardemail.net/api for more information

**Comment by niftylettuce** [comment]
cc @AquiGorka @aslafy-z

**Comment by niftylettuce** [comment]
Major overhaul of the API btw!  It now has responses/request examples, way more documentation too.

cc @AquiGorka @aslafy-z

**Comment by AquiGorka** [comment]
Sweet!
