### ISSUE TITLE
Too many login attempts - Send Mail As using Gmail

### ISSUE THREAD

**Issue by nicholaskajoh** [forwardemail/free-email-forwarding#209]
I'm getting the following error when trying to add a _send mail as_ email address to Gmail.

![Screenshot from 2020-03-05 08-31-43](https://user-images.githubusercontent.com/17048405/75958900-7308ae00-5ebd-11ea-8d04-7f59d242839e.png)

Does this have anything to with the number of people using your service? Or maybe I'm missing something? I'm following [this guide](https://forwardemail.net/en/faq?domain=trafficlogic.co#how-to-send-mail-as-using-gmail).

**Comment by niftylettuce** [comment]
Hard refresh or try incognito?

On March 5, 2020 7:52:52 AM UTC, Nicholas Kajoh <notifications@github.com> wrote:
>I'm getting the following error when trying to add a _send mail as_
>email address to Gmail.
>
>![Screenshot from 2020-03-05
>08-31-43](https://user-images.githubusercontent.com/17048405/75958900-7308ae00-5ebd-11ea-8d04-7f59d242839e.png)
>
>Does this have anything to with the number of people using your
>service? Or maybe I'm missing something? I'm following [this
>guide](https://forwardemail.net/en/faq?domain=trafficlogic.co#how-to-send-mail-as-using-gmail).
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/forwardemail/free-email-forwarding/issues/209

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by nicholaskajoh** [comment]
I just tried incognito. The same error. 😩

**Comment by nicholaskajoh** [comment]
I generated a new app password. Still no luck!

**Comment by niftylettuce** [comment]
This seems limited to being an issue with your configuration, Gmail account, or something localized on your end.  No it is not an issue with our service.
