### ISSUE TITLE
Multi recipients in web interface not working

### ISSUE THREAD

**Issue by backbone2k** [forwardemail/free-email-forwarding#212]
Hi,
when I configure multiple recipients for an alias only the first one in the list is getting an email. I have tested this by switching the first with the second alias. 

Example: alias@domain.net
Alias1: someone@freemailer.com
Alias2: someoneelse@freemailer.com

In this case a mail sent to alias@domain.net only hits the someone@freemailer.com mailbox
When I switch Alias1 and Alias2 in their order - only one mail for someoneelse@freemailer.com is delivered. 

I am not sure if this also happens when maintaining the aliases in TXT records.

Regards!

**Comment by mkaminsky** [comment]
I'm seeing the same issue using the web interface/Enhanced Protection version.

I tried to look into what might be going on.  The following code seems to transform the database alias -> recipient mappings into TXT record-style entries.  I'm hypothesizing that this code is then used by the actual forwarding system, but I didn't have time to look into how this all fits into the larger system.

https://github.com/forwardemail/forwardemail.net/blob/ebbe95cf71efcceb7e23a92ca52dca4bb89d532c/app/controllers/api/v1/lookup.js#L61-L63

The code appears to concatenate all of the recipients as follows (using @backbone2k 's example):
`    alias:someone@freemailer.com,someoneelse@freemailer.com`
Based on the FAQ entry about multiple recipients, I would have thought the result should be:
`    alias:someone@freemailer.com,alias:someoneelse@freemailer.com`
(repeating the "alias:" part).

Based on how the forwarding engine seems to parse these mappings, I can see why perhaps only the first recipient would get the email.

Thanks!

**Comment by niftylettuce** [comment]
@mkaminsky 	you rock.  thanks so much, deploying the fix now.

sorry have been so busy, we are pretty heads down at OurHarvest.com with everything going on and I haven't had time to dedicate to open source as much.

**Comment by niftylettuce** [comment]
Fix is deployed 🎉

**Comment by niftylettuce** [comment]
https://github.com/forwardemail/forwardemail.net/commit/195fad517956150a8b3e8b96d2d96f18ca790b6d

**Comment by mkaminsky** [comment]
Sorry for the delayed reply...seems to be working great!  Thanks!
