### ISSUE TITLE
Better protect account / login with MFA/2FA/FIDO2 and change log

### ISSUE THREAD

**Issue by backbone2k** [forwardemail/free-email-forwarding#213]
Because this service can get crucial from a digital life perspective, tampering the aliases/forwards can be a real threat. 

It would be great to see some protection to the administrative account with at least TOTP Tokens or better FIDO2 support for logging in.

Also having some sort of optional alerting / audit logging for changes would also be great to detect possible tampering on an account

Is there something on your backlog for this type of protection?

**Comment by niftylettuce** [comment]
We have 2FA already ready to go and I believe @shaunwarman will be implementing.

**Comment by niftylettuce** [comment]
And yes, we will have auditing in place thanks to @spence-s work with https://github.com/Spence-S/mongoose-human-diff-plugin and https://github.com/Spence-S/human-object-diff

**Comment by niftylettuce** [comment]
Closing for organization purposes in favor of #189 where this will be added very shortly as a release checklist item.  Please follow/subscribe to that issue for further updates.
