### ISSUE TITLE
Add OAR Header because Outlook.com puts forwarded mails into Junk

### ISSUE THREAD

**Issue by backbone2k** [forwardemail/free-email-forwarding#216]
I constantly have mails forwarded through forwardmail.net in my outlook.com junk filter.

I checked a little bit deeper and I think the reason is how the anti spoofing in Outlook / o365 works.

Also refereing to some docs for dmarc I think adding an Original Authentication Header could mitigate this issue.

I do not know if this was brought up already or if you actually adding the OAR header - but I cannot see one for me. What I can observe is, that outlook.com fails authentication a forwarded mail:

Authentication-Results: spf=none (sender IP is 138.197.213.185)
 smtp.mailfrom=t-online.de; outlook.de; dkim=pass (signature was verified)
 header.d=forwardemail.net;outlook.de; dmarc=none action=none
 header.from=t-online.de;compauth=fail reason=001

The original mail was sent from t-online.de and was forwarded to outlook.de
This mail does not have an OAR header - so outlook.com does not know if fordwardmail.net has made an SPF/DKIM alignment check or not. 

More infos I found here:
https://dmarc.org/wiki/FAQ#I_operate_a_mailing_list_and_I_want_to_interoperate_with_DMARC.2C_what_should_I_do.3F

And OAR IETF document here:
https://tools.ietf.org/html/draft-kucherawy-original-authres-00

what do you think?

regards,
backbone2k

**Comment by james-fry** [comment]
I used to have this issue with Outlook.com when I used mailgun for forwarding. When I started using forwardemail.net actually it worked well for a few weeks but outlook.com is now blocking **all** my forwarded emails :( I have reverted to using a wildcard alias forwarding to both outlook.com and another webmail provider.

I raised a support ticket with outlook.com, and they told me to raise a ticket here:
https://support.microsoft.com/en-us/supportrequestform/8ad563e3-288e-2a61-8122-3ba03d6b8d75
I assume this will help to get the forwardemail.net IPs unblacklisted, but I think I'd need @niftylettuce help to do this.

Maybe OAR support will help to keep forwardemail.net from being blacklisted in the future.
