### ISSUE TITLE
Direct delivery possible without "via"/"on half" etc? Add DKIM?

### ISSUE THREAD

**Issue by nolandg** [forwardemail/free-email-forwarding#217]
Just wondering if it is possible to receive emails forwarded by forwardemail.net directly without the "via"/"on behalf" etc? Would a DKIM record achieve this to allow forwardemail to send directly from my domain? 

The only records I have currently are:
`v=DMARC1; p=none; pct=100; rua=mailto:re+ulcezjh9fgd@dmarc.postmarkapp.com; sp=none; aspf=r;`
`forward-email-site-verification=KJhNht44DH`
`v=spf1 a mx include:spf.forwardemail.net -all`

In the example below, the `prfarmers.ca` receiving address is the domain I've setup with forwardemail.net. I receive it in Gmail with the "via".

![image](https://user-images.githubusercontent.com/5650727/78277780-e6580c80-74c9-11ea-81d3-b0df8a734ae3.png)

As per the FAQ, I signed up for Postmark to send me a DMARC digest every week. Does it have anything to do with everything failing? My domain passes the validation tests on the forwardemail.net site, not sure what else I have to do.

![image](https://user-images.githubusercontent.com/5650727/78279721-d42b9d80-74cc-11ea-8399-53732ae22f7b.png)

**Comment by niftylettuce** [comment]
Gmail does this and there's nothing we can do.

Note that I just released v6.0.1, which added SRS, fixed DMARC, fixed DKIM, improved speed, and numerous other fixes.
