### ISSUE TITLE
forwardemail.net always blacklisted with Microsoft

### ISSUE THREAD

**Issue by davidkarlsen** [forwardemail/free-email-forwarding#218]
I send a bit of email through forwardemail.net, but these usually bounce when sending to outlook accounts. We have all the correct SPFs in place - but it seems to be tied to the IPs having been blacklisted - not our domain.

**Comment by niftylettuce** [comment]
Microsoft has been an absolute pain to work with, I'm rolling out new IP's and resubmitting blacklist removal requests.

**Comment by davidkarlsen** [comment]
What causes this? Does spam/illegitimate mail to be sent from the ip-addresses to cause this?

**Comment by davidkarlsen** [comment]
I see new address was added for mx1 - but it will still go into blacklist after a few hours.

**Comment by james-fry** [comment]
> Microsoft has been an absolute pain to work with, I'm rolling out new IP's and resubmitting blacklist removal requests.

Its the same with other forwarding services, too. Its one of the reasons I raised this issue:
https://github.com/forwardemail/forwardemail.net/issues/12
Is there a problem with forwardemail being (mis)used to deliberately send spam? (as opposed to forwarding spam sent to users email addresses)

**Comment by james-fry** [comment]
> I see new address was added for mx1 - but it will still go into blacklist after a few hours.

This would explain why some of my mail started getting through to my outlook.com address. I currently fwd to both outlook and another webmail.

**Comment by niftylettuce** [comment]
This problem will be alleviated very soon.  I invented a cool tactic I'm going to implement to work around with monitoring pretty easily.

**Comment by james-fry** [comment]
Thanks for the update. You will have some very happy users in my family ! :)

**Comment by niftylettuce** [comment]
Working as fast as I can, hoping to have this all done by Friday.

**Comment by james-fry** [comment]
Thanks @niftylettuce  - what is the fix? How does it get around IP blocks on outlook.com? (or prevent the blocks being triggered in the 1st place?)

**Comment by niftylettuce** [comment]
I changed IP's.  I also am implementing stricter spam controls and
monitoring abuse@ and postmaster@ ARF response formats closely.  I've
signed up for pretty much every feedback loop service that there is, for
every single provider out there.
