### ISSUE TITLE
Add status page w/reliability+uptime ping tests

### ISSUE THREAD

**Issue by niftylettuce** [forwardemail/free-email-forwarding#22]

**Comment by MattIPv4** [comment]
@niftylettuce Hey, would you like help with this?
I'm sure I can talk to some people at Statuspage and see fi they'd be happy to hook you up :)

**Comment by niftylettuce** [comment]
That'd be fantastic!

**Comment by MattIPv4** [comment]
@niftylettuce Could I possibly be added as a collaborator so that I appear as "part of" the project for Statuspage so they know I am contacting them properly ob behalf of the project? :D

**Comment by MattIPv4** [comment]
Also, do you have a list of what service components you’d like on the status page?

And what domains/URLs I should ping in Pingdom for uptime and response time metrics?

**Comment by niftylettuce** [comment]
mx1.forwardemail.net
mx2.forwardemail.net
forwardemail.net

**Comment by niftylettuce** [comment]
Sorry for the delay - just did a major improvement and overhaul, see <https://github.com/niftylettuce/forward-email/issues/101#issuecomment-471938509> for a detailed explanation.

**Comment by MattIPv4** [comment]
@niftylettuce Could I be added to the org?
And will it just be a ping on those three domains to check uptime?

**Comment by niftylettuce** [comment]
@MattIPv4 answers below:

1) HTTP GET with response code of `200` for `forwardemail.net` should be OK
2) `telnet mx1.forwardemail.net 25` followed by `helo` (optionally `ehlo`) and then `quit` some way to telnet or EHLO
3) repeat (2) above but for `mx2.forwardemail.net`

I don't have an org setup yet for this repository/project 😦 

P.S. I tried to get a hold of @indus from JS.ORG, since he is using ImprovMX instead of ForwardEmail.net - maybe you can ping him to switch to something private and secure, AND OPEN SOURCE! 😄 ?

**Comment by MattIPv4** [comment]
@niftylettuce Awesome.

You should be able to add me directly as a collaborator to this repo, which should hopefully be enough to convince any company looking in that I'm here to help as part of the project :)

With regards to js.org - I suggested improv over this simply because it keeps the target email addresses private, whereas with this they're public in txt records. I personally use a mixture or improv and forwardemail throughout my own projects.

**Comment by aaronstuder** [comment]
Here ya go ;)

https://hetrixtools.com/r/4d2acef1653fa0bf0c32d87627939ac3/

**Comment by niftylettuce** [comment]
@aaronstuder thanks 👍 that's nice to have for now!  I have a status page that I'll launch on v2.0.0 but that is really really helpful for a temporary solution until then.  Looks nice

**Comment by MattIPv4** [comment]
Is there still a plan to move this to its own org at some point?

**Comment by niftylettuce** [comment]
Yes, eventually niftylettuce will become an organization.

**Comment by ParveenBhadooOfficial** [comment]
Did you checked this 
https://github.com/CachetHQ/Cachet
https://github.com/bazzite/statusfy
or just see https://github.com/ivbeg/awesome-status-pages#opensource

**Comment by niftylettuce** [comment]
Yes @ParveenBhadooOfficial but they do not satisfy my requirements.

Closing for organization purposes in favor of #189 where this will be added very shortly as a release checklist item.  Please follow/subscribe to that issue for further updates.
