### ISSUE TITLE
Add diagnostic information into extra headers.

### ISSUE THREAD

**Issue by kcolford** [forwardemail/free-email-forwarding#220]
Hey, so sometimes there are hiccups in getting emails forwarded or we're not quite sure why it ended up using "friendly from" instead of the default. Adding stuff like a X-Original-From header to emails or similar would help with that a lot; especially since if the sender includes a "Reply-To" and it goes through "friendly from" then you can't get the original from address at all.

**Comment by niftylettuce** [comment]
I'll add X-Original-From in the next release

**Comment by niftylettuce** [comment]
X-Original-From has been added and deployed, along with a few other things.

I've also improved DMARC compliance, and done a few other things to ensure emails go through.  Also setting up new IP addresses to alleviate Microsoft issues.
