### ISSUE TITLE
Subdomains email forwarding

### ISSUE THREAD

**Issue by idish** [forwardemail/free-email-forwarding#221]
Hello,
I've just tried to set up email forwarding for my subdomain. Is there any support to forward emails from a subdomain and not an apex? It doesn't seem to work for me, unfortunately.

Thank you for the great work!
Idan.

**Comment by niftylettuce** [comment]
Yeah subdomains work, may need to update docs slightly on this though.  If you find anything wrong in docs let me know, but it def works

**Comment by idish** [comment]
Would I have to add my domain normally and the TXT and MX records should be directed to the subdomain instead of the apex domain?

**Comment by idish** [comment]
Also, might be a little off topic, but Is there any reason to set up an SPF record to forwardemail.net in case I'm sending emails using the another service? 
I'm currently using the service to receive forwarded emails, when I reply to them, another smtp service is going to be used.

**Comment by niftylettuce** [comment]
Closing for organization purposes in favor of #189 where this will be added very shortly as a release checklist item.  Please follow/subscribe to that issue for further updates.
