### ISSUE TITLE
Changing the "From" address

### ISSUE THREAD

**Issue by idish** [forwardemail/free-email-forwarding#222]
Is there any way to keep the from address as the original sender of the email? 
As currently these are the details of the email I receive using the service:
<img width="403" alt="Screen Shot 2020-04-22 at 14 46 47" src="https://user-images.githubusercontent.com/5266462/79978625-e172f100-84a8-11ea-96e0-e4a00242f97e.png">

Problem is, when replying to that email, there is going to be a quote that the sender is going to see and that shows that the original message was sent from "forwardemail.net" and not from the original author (i.e ..@gmail.com). 
 
<img width="500" alt="Screen Shot 2020-04-22 at 14 53 58" src="https://user-images.githubusercontent.com/5266462/79978843-3d3d7a00-84a9-11ea-8b77-cfe9c18e378b.png">

I think that these kind of emails might arise a suspicion from users whom we reply to.
Is there any way to fix that without altering the quote manually?

Thanks!

**Comment by niftylettuce** [comment]
We do a friendly-from rewrite to ensure 100% DMARC compliance (on forwarded messages) IFF needed.  If you provide more information on the sender and the recipient, I can look into this further for you, email niftylettuce@gmail.com with this info if you could.
