### ISSUE TITLE
plus (+) addresses for recipients no longer work

### ISSUE THREAD

**Issue by mkaminsky** [forwardemail/free-email-forwarding#225]
As of a couple of days ago, plus address (+) extensions don't seem to be working for me.

I've tested both of the following cases:
 * Aliases that do _not_ have a + extension in the recipient list, e.g., `hello@example.com -> me@gmail.com`.   Sending to `hello+list@example.com` goes to `me@gmail.com` instead of `me+list@gmail.com`.
 * Aliases to _do_ have a + extension, e.g., `hello@example.com -> me+hello@gmail.com`.  Here too, sending to `hello@example.com` goes to `me@gmail.com` instead of `me+hello@gmail.com`.

Both of these cases worked until a couple of days ago.  Looking at the changes, I'm guessing it's this commit which modifies the + address behavior:  https://github.com/forwardemail/free-email-forwarding/commit/6147e033a0f1bd576a8caea800b2ef2a944a6d8a

Thanks!

**Comment by niftylettuce** [comment]
Will follow up asap.

**Comment by niftylettuce** [comment]
@mkaminsky I've just deployed v6.1.8 - can you test again?

**Comment by mkaminsky** [comment]
@niftylettuce Tests work.  Thank you!

**Comment by niftylettuce** [comment]
Fantastic, let me know of any further issues, feature requests, or feedback in general. Thank you.
