### ISSUE TITLE
[feat] wildcard + regex aliases

### ISSUE THREAD

**Issue by mkaminsky** [forwardemail/free-email-forwarding#226]
This is another Mailgun-inspired feature.

Right now, there is a single catchall alias (*) that matches addresses that aren't matched by another exact alias.

I would find it useful to be able to use wildcards in my aliases.  I can think of think of two variants:
 - Aliases can contain simple glob patterns:
     - `list-*@example.com -> me+list@gmail.com`
     - `*.someone@example.com -> someone@gmail.com`
 - Recipient list can additionally reference matched patterns:
     - `list-(*)@example.com -> me+list.$1@gmail.com`

Of course, there are details about the exact syntax, making sure + addressing still works, etc.  For me, simple glob patterns are likely sufficient, as opposed to full regexps.

Unfortunately, this feature probably implies some extra complexity by requiring aliases to have priority since it's possible for an incoming address to match more than one wildcard address.  Does the address trigger both sets of aliases, the one with a higher priority, etc.?

That said, if this feature does become a reality, one useful addition to the web interface might be a web form to test addresses.  The user could type in an address like `list-news@example.com` and the site would say: That forwards to `me+list.news@gmail.com`.

Thanks again for the great service!

**Comment by niftylettuce** [comment]
I have plans for this, I will be supporting regular expressions / globs

**Comment by Kwal** [comment]
This feature would be really great - is this something that you're considering for the v8 release?

**Comment by niftylettuce** [comment]
yeah, might get it out sooner.

**Comment by rintaun** [comment]
this would be very helpful for essentially "domain aliases", e.g. you have the same addresses at `example.com` and `example.net`. if you consider `example.com` the canonical domain, `example.net` could define `(*)@example.net -> $1@example.com` or something similar.

**Comment by rintaun** [comment]
regex aliases would also make defining some repetetive, administrative aliases that i use on all my domains much easier, e.g. `(abuse|security|hostmaster|postmaster|webmaster|etc...)@example.com -> admin@example.com`

**Comment by straxhaber** [comment]
Do you have an update on this?

**Comment by pierstitus** [comment]
+1, would be a great feature to have!

**Comment by niftylettuce** [comment]
Regex filter support and documentation has been deployed 🎉 

* FAQ @ https://forwardemail.net/en/faq#do-you-support-regular-expressions-or-regex
* Email Forwarding Regex Pattern Filter @ https://forwardemail.net/en/email-forwarding-regex-pattern-filter

**Comment by mkaminsky** [comment]
Terrific--thanks for implementing this feature!  This is great.

Quick question:  what happens if an address matches more than one alias:  a regex pattern and a plain alias, or two regex patterns, etc.?   It looks like the system forwards to both (all) recipients where there is a match, but I wanted to confirm.

The use-case that I'm thinking about is as follows:  a generic alias, `/^list-(.+)$/`, that goes to one recipient address, and a "exception-to-the-rule" alias, `list-abc`, that goes elsewhere.

**Comment by mnpenner** [comment]
It appears I can't match the `+` in an address like `bounce+00cdaa.201fc-katelyn=foo.com@bar.com`. Was trying like this:

![image](https://user-images.githubusercontent.com/1112998/166085897-64cb3fa1-d78b-4bf7-896f-d20c96aec30b.png)

Will have to settle for `/^bounce/`
