### ISSUE TITLE
Possible phishing vector attack.

### ISSUE THREAD

**Issue by cnicodeme** [forwardemail/free-email-forwarding#227]
Cyril from [ImprovMX](https://improvmx.com) here (for full disclosure).

We've identified an important issue that can lead to a possible phishing vector attack.

The issue is located at the friendly from rewrite when DMARC might fails (Starting at line [1132](https://github.com/forwardemail/free-email-forwarding/blob/master/index.js#L1132) of the current code).

When the incoming email does not have a (valid) DKIM Signature, you change the original `From` to the `noReply` email defined in the config. For instance, you rewrite to "no-reply@forwardemail.net".

The issue here is that I can very easily send an email from a domain that enforces DMARC, without a DKIM signature, with the following content :

```
Subject: Your credit card was declined on ForwardEmail.net
Body: Hi,
We noticed an issue with your credit card on ForwardEmail. Your last payment has been declined, and your emails won't be forwarded anymore.
 
Please update it by clicking on the following link:
https://fake-forwardemail.net/update/
```

This email will have the `From` header rewritten to be "no-reply@forwardemail.net", which will then be **SPF and DKIM valid, and pass DMARC validation**. From the point of view of a client, this email will be a legitimate Forwardemail.net, thus trusting the link inside, and accessing a fake website.

It's a basic example, but you can easily see the level of risk here (asking for payment, credit cards, etc).

In order to fix this issue, possible solutions can be implemented:

 * Re-write the email's content to add an alert saying that the FROM was re-written. We are not fan of this solution because it means tampering with email content and that's not respectful toward the users.
 * Use a different domain name for the rewrite, like "rewrite-forwardemail.net". The nice thing about this is that you can host a small FAQ page on this domain to explain why you have to rewrite such emails.
 * Refusing emails that don't have a valid DKIM but enforce DMARC. (this is more drastic)

I remain available if you have any questions. I'm happy to help!

**Comment by niftylettuce** [comment]
I already know of this, and this is why I made SpamScanner, https://github.com/spamscanner/spamscanner.

**Comment by niftylettuce** [comment]
@cnicodeme if you're interested in working together on SpamScanner please let me know, I'm available at niftylettuce@gmail.com and we also have a Slack channel.
