### ISSUE TITLE
"chat" badge is dead in README

### ISSUE THREAD

**Issue by 178inaba** [forwardemail/free-email-forwarding#231]
<img width="356" alt="スクリーンショット 2020-07-09 0 41 05" src="https://user-images.githubusercontent.com/12012186/86939717-e4fb4780-c17c-11ea-86de-46812f9f370e.png">

And https://slack.crocodilejs.com/ is application error.

<img width="587" alt="スクリーンショット 2020-07-09 0 42 20" src="https://user-images.githubusercontent.com/12012186/86939876-107e3200-c17d-11ea-81ab-54e3b9b70258.png">

**Comment by niftylettuce** [comment]
yeah the heroku app went down for some reason, it's on my TODO's to fix, thanks for reminder

**Comment by niftylettuce** [comment]
Chat badge is fixed
