### ISSUE TITLE
forwardemail shouldn't forward X user's mail to all XYZ users, how to solve this?

### ISSUE THREAD

**Issue by asharamseervi** [forwardemail/free-email-forwarding#234]
Hello community,

I'm able to configure and send mails with https://forwardemail.net but I'm unable to solve following scenario, I've gone through FAQs but didn't noticed, how to achieve this:

**Use Case:** Lets assume, I'm configuring mail forwarding for my team, which is 6 member team, 3 departments (Support, Development & Sales), and my domain is `domain.io`, seems right!

I've configured TXT records as follows:
```
@  | 600 | TXT | forward-email=mojito@domain.io,mojito@gmail.com <developer>
@  | 600 | TXT | forward-email=martini@domain.io,martini@gmail.com <support>
@  | 600 | TXT | forward-email=sangrita@domain.io,sangrita@gmail.com <sales>
@  | 600 | TXT | forward-email=negroni@domain.io,negroni@gmail.com <sales>
@  | 600 | TXT | forward-email=margarita@domain.io,margarita@gmail.com <developer>
@  | 600 | TXT | forward-email=cosmopolitan@domain.io,cosmopolitan@gmail.com <developer>
```

**Issues:** When I'm sending a test mail to `mojito@domain.io` this also sent to all other users, while it should only needs to send `mojito@gmail.com`. How to achieve this?

In addition to this, I'll be glad if I can achieve sending a mail to group mail address, like if someone mails to `developer@domain.io` this should forward mails to all 3 who have listed as developer. How I can achieve all together with same `domain.io`, can someone help me with correct DNS settings, if I am missing something!

**Comment by niftylettuce** [comment]
You have set your records up incorrectly.

For example, `forward-email=mojito@domain.io,mojito@gmail.com` should instead be `forward-email=mojito:mojito@gmail.com`.

See the FAQ.  Let me know otherwise.

You can always upgrade to a paid plan and use our managed aliases feature, which will eliminate any confusion.

**Comment by asharamseervi** [comment]
Thankyou @niftylettuce for prompt support & this awesome tool.

PS: A small line in FAQ have helped me, if it is written like "`forward-email=<desired_address>:<forwarding_to@domain.io>`".
I wrongly interpreted colon, I thought it's a dot (commonly used as separator in mail address), and you made some type. My bad.

**Comment by niftylettuce** [comment]
No prob- can probably make that clearer in future.  PR Welcome!
