### ISSUE TITLE
Error when trying to change email

### ISSUE THREAD

**Issue by mdctleo** [forwardemail/free-email-forwarding#236]
Error happens when trying to confirm a change of email address.

## Steps
My Account -> Profile -> Change email address -> save -> click on confirmation link from email in the new email address

## Screenshot

![118095637_2733961883516651_8507090841595860591_n](https://user-images.githubusercontent.com/31061195/90996125-a970dd00-e572-11ea-85f6-8f86a9b7dd0f.png)

**Comment by niftylettuce** [comment]
Sorry give me like 2 minutes this will be fixed.

**Comment by niftylettuce** [comment]
This happens because you're not logged in by the way.

**Comment by niftylettuce** [comment]
This is now fixed, please try again @mdctleo.  Thanks for the heads up.
