### ISSUE TITLE
Emails forwarded to Yahoo always end up in spam

### ISSUE THREAD

**Issue by shvchk** [forwardemail/free-email-forwarding#237]
Yahoo always puts emails forwarded to them in spam. DKIM and SPF pass. I can mark message as not spam, but that only affects one particular sender. I've sent raw email to @niftylettuce, maybe it would help. Or maybe Yahoo just has paranoid spam rules :grimacing:

**Comment by niftylettuce** [comment]
I would steer clear of Yahoo.  They were an early pioneer, but now they've lagged so far behind in every respect, especially privacy.  I'm guessing their filters are set off on content or mixed language, and I'm guessing they don't even have ARC implemented.
