### ISSUE TITLE
Is this an ad or is this an NPM package? In that case how do I use it and where are the docs

### ISSUE THREAD

**Issue by informathemusic** [forwardemail/free-email-forwarding#239]
The title says it all

**Comment by niftylettuce** [comment]
Your sense of entitlement should go elsewhere

**Comment by informathemusic** [comment]
If this isn't an NPM package, then it has nothing to do in the NPM
registry. Just get it out already.
I'm looking for real email forwarding npm packages, that i can use
efficiently in my projects, not a living ad, and if it's not the case then
you should highly consider getting a more accurate readme

**Comment by niftylettuce** [comment]
As I said, your entitlement in open source is not welcome here.  If you spent the time to read and actually look before asking, you would see this is a published npm package.  You are now banned.
