### ISSUE TITLE
mx1.forwardemail.net is down

### ISSUE THREAD

**Issue by JSPSolvent** [forwardemail/free-email-forwarding#243]
Hello,
http://mx1.forwardemail.net/ is down since Jan. 7th 2021, especially with forwarding to **hotmail.com** accounts, forwarding to gmail accounts looks like a 50-50 chance with long delays. Keep getting this "undeliverable" email from outlook.com:

mx1.forwardemail.net rejected your message to the following email addresses:
XXXX@mailsire.com

**mx1.forwardemail.net** gave this error:
Remote server returned an error -> 550 Message was sent successfully to XXXX@mailsire.com, Error for hotmail.com of "This message has been retried the maximum of (10) times and has permanently failed."

**Comment by niftylettuce** [comment]
It is not down, Microsoft / Live / Hotmail listed the IP in blacklist falsely and it's being taken care of, I will share an update once it's resolved.

**Comment by niftylettuce** [comment]
We have heard from Microsoft and Outlook/Live/Hotmail issues are resolved and should go into effect within next 12-24 hours if not sooner.  If you continue to have issues after 24-48 hours please contact us.
