### ISSUE TITLE
Hey nifty 😢... Help me because I use free domain because I'm poor..

### ISSUE THREAD

**Issue by sayantan300** [forwardemail/free-email-forwarding#246]
I just got the email to upgrade to premium.. I don't have money that's why I use .ga domain... Please understand the problem with me... If u think my domain is a spam, u can delete my email from ur site, but if not, please help... Domain: [rovelstars.ga](https://rovelstars.ga)

**Comment by sayantan300** [comment]
@niftylettuce

**Comment by niftylettuce** [comment]
Please email niftylettuce@gmail.com or support@forwardemail.net regarding this
