### ISSUE TITLE
Forward emails sending to AOL get marked as spam.

### ISSUE THREAD

**Issue by muhupower** [forwardemail/free-email-forwarding#248]
Hello,

This is happening to my forwards sending to AOL.

They are all marked as spam in AOL and I can't even setup a filter in AOL bc its so antiquated to never mark it as spam.

I am getting this message in the original headers:

Received-SPF: softfail (domain of transitioninggmail.com does not designate 138.197.213.185 as permitted sender)

The DNS records are all setup correctly, but maybe bc its AOL I need to add something different for the SPF?

Please help, i submitted a donation,  thanks
-Owen

**Comment by muhupower** [comment]
Well, this is still happening for me.. aol email inboxes will not get a forward or nothing at all... not even going to spam... and no help from developer?

**Comment by niftylettuce** [comment]
Please send an email to support@forwardemail.net along with emails that have been attempted to be sent (in raw source format as an attachment or something if possible).  That way I can help debug further.
