### ISSUE TITLE
regex matching support

### ISSUE THREAD

**Issue by qnxor** [forwardemail/free-email-forwarding#250]
I'm very interested in regex matching as it's quite essential these days for anyone owning domains with less than trivial requirements (think company, etc). Privacy is important and most forwarding services fail miserably, as does the free version of Forward Email since that exposes the email addresses in the DNS lookup which defeats the whole purpose too (\*).

I'm interested in regex support for the "enhanced" version and I'm happy to look into adding support for it via a PR. Before I delve into it myself - is the code for the "enhanced" version also available on Github?

(\*) actually, the "free" version seems like a gift for spammers, as all they have to do is parse for forward-email TXT dns entries to collect valid email addresses and spam away.

p.s. I did find this PR https://github.com/forwardemail/free-email-forwarding/pull/245 but fails to meet my requirements as explained above

**Comment by niftylettuce** [comment]
Regex filter support and documentation has been deployed 🎉 

* FAQ @ https://forwardemail.net/en/faq#do-you-support-regular-expressions-or-regex
* Email Forwarding Regex Pattern Filter @ https://forwardemail.net/en/email-forwarding-regex-pattern-filter
