### ISSUE TITLE
Did the webhook payload change?

### ISSUE THREAD

**Issue by gunar** [forwardemail/free-email-forwarding#253]
My app broke today. It receives webhooks from my paid forwardemail.net account, and it _seems_ that the payload may have changed. I need to spend more time debugging before I can tell you exactly what changed and how it got broken, but thought I'd mention it early in case other people have the same problem.

Currently wondering if it has anything to do with this change: 4024455a0bef9e245e82bfef96dc44989172703b

**Comment by gunar** [comment]
It _seems_ the payload hasn't changed but the header `Content-Type` did—from `application/json` to `application/x-www-form-urlencoded`. Although the content is still JSON so I think there's a mismatch.

**Comment by niftylettuce** [comment]
The payload didn't change but the content-type did apparently from superagent, I'm looking at this now

**Comment by niftylettuce** [comment]
deploying fix now, thanks and sorry that was overlooked.   we now have a team - and we'll have way more alerts, features, and monitoring, and tests very soon to catch this in advance!
