### ISSUE TITLE
error

### ISSUE THREAD

**Issue by guoliyuan8899** [forwardemail/free-email-forwarding#256]
My domain name mailbox can't receive mail.
Unable to log in to the website.
I logged in through Google.

**Comment by ElliotAlderson02** [comment]
Can confirm. Unable to Receive mails or Login

**Comment by guoliyuan8899** [comment]
When can it be repaired?

**Comment by guoliyuan8899** [comment]
I'm afraid of missing important emails.

**Comment by niftylettuce** [comment]
Emails will be auto-retried, there was a timeout issue with our database and we have fixed it moving forwards.

**Comment by guoliyuan8899** [comment]
During the error. The mail will be sent again, right?

**Comment by niftylettuce** [comment]
> Emails will be auto-retried

**Comment by guoliyuan8899** [comment]
thank you. I thought I was going to miss some mail.

**Comment by guoliyuan8899** [comment]
It shouldn't be a big problem. I'll check my email later. thank you very much.
