### ISSUE TITLE
Friendly-From Rewrites Are Still Required In Some Cases

### ISSUE THREAD

**Issue by hagai-helman** [forwardemail/free-email-forwarding#257]
I took a close look at [this issue](https://github.com/forwardemail/forwardemail.net/issues/102), and it appears that:

1. Gmail currently does not trust ForwardEmail's ARC authentication results;
2. As a result, messages without DKIM but with a `reject` DMARC policy are rejected by Gmail when forwarded (from the recipient's point of view, they just never arrive).

I assume that such messages are also rejected by other mail services.

It seems to me that the best way to ensure deliverability right now is to avoid relying on the receiving mail service both (1) implementing ARC, and (2) trusting ForwardEmail. Instead, in the case of a message without DKIM that has a `reject` (and maybe also `quarantine`) DMARC policy, it's probably best to do a friendly-from rewrite.

See also [this discussion](https://github.com/trusteddomainproject/OpenARC/issues/129) in OpenARC.

**Comment by titanism** [comment]
This issue is now resolved.
