### ISSUE TITLE
Receiving SPF softfail in Gmail

### ISSUE THREAD

**Issue by spajak** [forwardemail/free-email-forwarding#258]
I'm receiving the following error in message headers when the message is sent from hotmail account:

```
Authentication-Results: mx.google.com; / ARC-Authentication-Results: i=2; mx.google.com;
    ...
    spf=softfail (google.com: domain of transitioning XXXXX@hotmail.com does not designate 104.248.224.170 as permitted sender) smtp.mailfrom=XXXXX@hotmail.com;
```

or this, when sent from yandex account:

```
Authentication-Results: mx.google.com; / ARC-Authentication-Results: i=2; mx.google.com;
    ...
    spf=softfail (google.com: domain of transitioning XXXXX@yandex.com does not designate 104.248.224.170 as permitted sender) smtp.mailfrom=XXXXX@yandex.com;
```

I have TXT record `forward-email=XXXXX@gmail.com`
And my TXT spf record includes ` include:spf.forwardemail.net`

**Comment by niftylettuce** [comment]
Yes this is expected.  The main reason for adding SPF record is for when we release SMTP support, so you'll already have it in advance, or for when you Send Mail As Gmail.  SPF softfail is expected when being forwarded, which is why we implement ARC seal.

**Comment by spajak** [comment]
You will have SMTP support? Great, will it be free?
