### ISSUE TITLE
Mailservers are blacklisted on UCEPROTECTL3

### ISSUE THREAD

**Issue by jpawlowski** [forwardemail/free-email-forwarding#259]
Hello,

I wanted to let you know that it seems some IPv4 addresses of the (receiving) e-mail servers are currently blacklisted:

<img width="393" alt="image" src="https://user-images.githubusercontent.com/75446/144760225-23cd2734-03fd-4071-bf66-230aecf04839.png">

<img width="397" alt="image" src="https://user-images.githubusercontent.com/75446/144760236-3854fcbf-4ae4-4e10-80e2-0b52832841cb.png">

Maybe this is something that shall be fixed somehow?

Cheers,
—Julian

**Comment by niftylettuce** [comment]
That is a scam blacklist where they make you pay even if you get falsely listed.  No major providers use them.  I'll look into removal again

**Comment by jpawlowski** [comment]
> That is a scam blacklist where they make you pay even if you get falsely listed.

Ouch! 😠

I didn't know that, thanks for explaining it to me!
