### ISSUE TITLE
How do I send email via SMTP after I buy it?

### ISSUE THREAD

**Issue by bbhxwl** [forwardemail/free-email-forwarding#261]
How do I send email via SMTP after I buy it?

https://forwardemail.net/ I bought it for 1 year, but I can only receive email, but I don't know how to send it. I don't want to use gmail

**Comment by niftylettuce** [comment]
We are releasing SMTP support in the near future, if you email smtp@forwardemail.net you will be signed up to be notified upon release.  In the interim, you could use Gmail or another service that lets you do send mail as feature.

https://forwardemail.net/en/faq#how-to-send-mail-as-using-gmail

**Comment by bbhxwl** [comment]
> We are releasing SMTP support in the near future, if you email [smtp@forwardemail.net](mailto:smtp@forwardemail.net) you will be signed up to be notified upon release. In the interim, you could use Gmail or another service that lets you do send mail as feature.
> 
> https://forwardemail.net/en/faq#how-to-send-mail-as-using-gmail

Will SMTP charge extra?

**Comment by niftylettuce** [comment]
I don't think so, but there will be limitations on storage probably
