### ISSUE TITLE
LICENSE: Change date is in future

### ISSUE THREAD

**Issue by onovy** [forwardemail/free-email-forwarding#263]
This date:

https://github.com/forwardemail/free-email-forwarding/blob/master/LICENSE#L18

is a bit in a future

**Comment by niftylettuce** [comment]
That's how the license works

**Comment by onovy** [comment]
yep sorry, i'm stupid :)

**Comment by niftylettuce** [comment]
No, this is inherently confusing, so I don't blame the issue filing (4 years or whichever comes first is the key phrase)
