### ISSUE TITLE
Catch-all if no other rules matched

### ISSUE THREAD

**Issue by devksingh4** [forwardemail/free-email-forwarding#264]
Hello all, 
Is there a way to create a catch-all global alias forwarding? I am looking to do the forwarding (I have part 1 setup already): 

### Part 1: 
* admin@domain1.com to john@gmail.com,jane@gmail.com
* help@domain1.com to john@gmail.com,smith@gmail.com
* webmaster@domain1.com to elon@gmail.com

### Part 2 (what I want to figure out):
* Any emails that did not match any previous rules, send to the same user @domain2.com

I saw that there is a global alias forwarding rule, however it is unclear in the docs if this rule will only trigger if there is no other matching TXT record. 

Thank you!

**Comment by rolltidehero** [comment]
This is a must-have feature for me also. Just curious before I started the install.

**Comment by titanism** [comment]
We already support global catch-all if no other rules matched.  We are adding an opt-in feature to exclude global catch-alls if other matches were found, and will ping you here once released.

**Comment by titanism** [comment]
RE: your comment:

> I saw that there is a global alias forwarding rule, however it is unclear in the docs if this rule will only trigger if there is no other matching TXT record.

Currently it will _always_ be used for forwarding if you have a global catch-all.

**Comment by zecanard** [comment]
I am very confused by this. I use a catch-all for my two domains, and the catch-all only forwards emails that do not have a more specific alias specified. If an email matches a more specific rule, the catch-all does not come into play.

So for instance, emails to `me@mydomain.com` only get forwarded by `forward-email=me:you@otherdomain.com`. They do **not** get forwarded by the catch-all rule `forward-email=otherdomain.com`.

[catch-all vs catch-leftovers](https://github.com/forwardemail/forwardemail.net/issues/161#issuecomment-1117623671) also confirms this.

I’m on the free plan, and my setup involves one forwarding rule per TXT record.

Is the behavior different if you specify both the specific forward **and** the catch-all in a single TXT record? Does it work differently on the Enhanced Privacy plan?

**Comment by titanism** [comment]
Sorry for the confusion in the past!

To clarify, global forwarding catch-alls **are only used if there are NO other matches found**.

**Comment by titanism** [comment]
We deleted the previous comment - the paid plans do in fact match free plans currently in this concept as mentioned in the comment above today.

**Comment by schultzter** [comment]
This is a great explanation, it should be added to the FAQ
