### ISSUE TITLE
[fix] Gmail reports unencrypted messages

### ISSUE THREAD

**Issue by gecko579** [forwardemail/free-email-forwarding#270]
## Describe the bug

**Node.js version:** 

**OS version:**  iOS 15.5

**Description:**  As of this morning Gmail is not encrypting forwarded email.

## Actual behavior

 Have been using forwardemail.net for over a year with no issue but this morning I started seeing the red “gmail did not encrypt” on gmail headers read in iOS reader

## Checklist

- [ ] I have searched through GitHub issues for similar issues.
- [ ] I have completely read through the README and documentation.
- [ ] I have tested my code with the latest version of Node.js and this package and confirmed it is still not working.

**Comment by titanism** [comment]
@gecko579 do you still receive this? have you tested again?

**Comment by gecko579** [comment]
NOW FIXED—many thanks indeed for the quick response!!

Matt

**Comment by titanism** [comment]
👍

**Comment by gecko579** [comment]
Broken again…

**Comment by titanism** [comment]
This is intermittent, we are working on a patch, one moment.

**Comment by gecko579** [comment]
Thanks, understood and appreciated

**Comment by titanism** [comment]
This issue should now be fully resolved now.  If you have further issues (e.g. more bounces or errors) please let us know.

**Comment by gecko579** [comment]
Thank you

**Comment by gecko579** [comment]
Just received two more unencrypted forwarded emails.

**Comment by titanism** [comment]
If you receive any more unencrypted emails after 8:30 PM ET (in 3 mins) today please email us at support@forwardemail.net
