### ISSUE TITLE
[feat] Use of PGP to encrypt forwarded mails

### ISSUE THREAD

**Issue by r3nor** [forwardemail/free-email-forwarding#275]
## Describe the feature

I would like to be able to import a PGP Public Key and be able to receive encrypted emails from ForwardEmail. SimpleLogin has this feature and it is pretty good to have.

## Checklist

- [x] I have searched through GitHub issues for similar issues.
- [x] I have completely read through the README and documentation.

**Comment by titanism** [comment]
<https://forwardemail.net/en/faq#do-you-support-openpgpmime-end-to-end-encryption-e2ee-and-web-key-directory-wkd>
