### ISSUE TITLE
[feat] Sort aliases table alphabetically by default

### ISSUE THREAD

**Issue by bretmartin** [forwardemail/free-email-forwarding#277]
## Describe the feature

My domain list (https://forwardemail.net/en/my-account/domains) lists my domains in alphabetical order by domain name.

It would be useful and clearer if domain alias lists (https://forwardemail.net/en/my-account/domains/[domain]/aliases) were similarly sorted alphabetically by default, for easier browsing.

I think the current alias sorting is just whatever order the API happens to return the data in. I'm not sure if the domain sorting is as returned by the API or if the front-end code is sorting the data.

## Checklist

- [x] I have searched through GitHub issues for similar issues.
- [x] I have completely read through the README and documentation.

**Comment by titanism** [comment]
@bretmartin will do

**Comment by titanism** [comment]
@bretmartin done!  check it out at <https://forwardemail.net/en/my-account/domains> (click on Aliases)

if you have any other feedback feel free to share here or email support@forwardemail.net

we also made the Aliases page way more mobile friendly too, and we made the FAQ have collapsible sections at https://forwardemail.net/faq

thx 🙏

**Comment by bretmartin** [comment]
@titanism These changes are all fantastic. I know the users I'm setting things up for will also appreciate them, especially the mobile-friendliness!
