### ISSUE TITLE
[feat] Support failing faster for unroutable address

### ISSUE THREAD

**Issue by xim** [forwardemail/free-email-forwarding#289]
## Describe the feature

Currently, if an email is sent to an unroutable address, the email is deferred (421).

I get that this can be helpful when first configuring a domain, but in a stable setting I'd prefer these to fail with `550 Unrouteable address`

Adding a configuration option for this, e.g. adding a config or by allowing aliases to be explicitly set to reject incoming email (so I can add a wildcard reject alias)

## Checklist

- [x] I have searched through GitHub issues for similar issues.
- [x] I have completely read through the README and documentation.

**Comment by titanism** [comment]
@xim thank you for the request!  we'll look at adding this &ndash; right now we're trying to ship calendars/contacts/newsletter support

**Comment by titanism** [comment]
This feature is now available.  You can use `!` (250), `!!` (421), or `!!!` (550) for a disabled alias.

This is supported on both free plan and paid plan.

Free plan: <https://forwardemail.net/faq#can-i-disable-specific-aliases>

Paid plan:
<img width="796" alt="Screen Shot 2024-07-25 at 3 05 36 AM" src="https://github.com/user-attachments/assets/51ae8691-e897-478a-a891-6ff7739da20f">

cc @xim

**Comment by xim** [comment]
I notice this isn't available for wildcard aliases; is there a way to get 550 errors for all addresses not explicitly configured?
