### ISSUE TITLE
SMTP Service not working

### ISSUE THREAD

**Issue by Artic6** [forwardemail/free-email-forwarding#294]
I have not been receiving emails for quite awhile using this service your monitoring reports everything is online but that is not the case - if I send an email using this service from my work account I’m currently getting this……

Reason: [{LED=421 Timeout - closing connection};{MSG=};{FQDN=104.248.224.170};{IP=104.248.224.170};{LRT=8/3/2024 4:58:56 PM}]. OutboundProxyTargetIP: 104.248.224.170.

the email was sent at 1758 I’ve still not received it because your servers are not processing SMTP requests

your status page says everything is 100% up which is actually incorrect, the port may be online but the email service is not

**Comment by titanism** [comment]
Hi there - this was most likely related to <https://status.forwardemail.net/incident/1201> (https://github.com/forwardemail/status.forwardemail.net/issues/1201)
