### ISSUE TITLE
add support for TXT record "forward-email-options=" and "pass-through-mx" option as a starter

### ISSUE THREAD

**Issue by ww7** [forwardemail/free-email-forwarding#44]
Like 
if address@ not in TXT listing than
mx*.forwardemail.net reject and email pass to the next MX server?

(i need to split couple of email addresses to different mail services)

**Comment by anistark** [comment]
👍 Same question. 
Will setting priorities work ?

**Comment by niftylettuce** [comment]
- [ ] Detect a (multi-line) TXT record on the domain named "forward-email-options=" which contains a comma separated list of options to enable for the domain's forward email settings
  - [ ] "pass-through-mx" - if enabled, this will check for additional MX servers on the domain that _are not_ of the root domain `forwardemail.net`, and if set, emails will be proxied through

**Comment by thebeardbe** [comment]
+1 for this request.

Sadly enough I'm not good with coding at all.

But I would love this feature as it is very handy to setup an e-mail that has to be sent to multiple addresses in the same domain when your provider doesn't give you this option.

For example I would want to have info@mail.com go aaa@mail.com and bbb@mail.com

This could be a pretty nice feature that is impossible to do even with for example gsuite. I guess you might win a lot of extra users of your service with this option.

**Comment by niftylettuce** [comment]
Keeping this open as I'd like to look at it again in the near future.

**Comment by niftylettuce** [comment]
Adding this to #189
