### ISSUE TITLE
[gmail sendAs] - 534 5.7.9 Please log in with your web browser and then try again

### ISSUE THREAD

**Issue by FGRibreau** [forwardemail/free-email-forwarding#48]
> 534 5.7.9 Please log in with your web browser and then try again. Learn more at https://support.google.com/mail/?p=WebLoginRequired q3-v6sm2883638qkf.77 - gsmtp

forward-email gmail sendAs feature stopped working today. I can't send email anymore and did not touch anything. 

I tried to generate a new [app password](https://myaccount.google.com/apppasswords) and the update it in gmail (the `password` field) but I get a `Authentication failed`.

Any idea what is going on?

**Comment by FGRibreau** [comment]
Oh I see, I tried to send a email to the forward-email address and got this back:

> 550 Please ensure the email service you are sending from either has SPF, DKIM, or is a top-ranked <30K Alexa.com domain. You can most likely resolve this problem by searching on Google for "$serviceName SPF DKIM setup" (be sure to replace $serviceName with your email service provider, e.g. "Zoho"). If you continue to have issues, please see https://forwardemail.net or file an issue on GitHub at https://github.com/niftylettuce/forward-email. We'd be glad to help out! -- @niftylettuce

It's weird because it was working before 🙄, I wonder why it has change since...

**Comment by FGRibreau** [comment]
forward-email seems to be blacklisted here:


| Blacklist | Reason | TTL | ResponseTime |  
| -- | -- | -- | -- | --
| LISTED | MAILSPIKE Z | 178.128.149.101 was listed  Detail | 120 | 0 | Ignore
| LISTED | SORBS DUHL | 178.128.149.101 was listed  Detail | 3316 | 141 | Ignore

**Comment by niftylettuce** [comment]
@FGRibreau those two entries come and go and can be inaccurate

**Comment by FGRibreau** [comment]
Related with:
- https://github.com/jhermsmeier/node-dkim/issues/2
- https://github.com/Flolagale/mailin/issues/132
