### ISSUE TITLE
ubuntu installation

### ISSUE THREAD

**Issue by nickpp** [forwardemail/free-email-forwarding#58]
Hi 
Trying to install forward-email on ubuntu. 
Node, NPM 
Other modules are ok. 
When i am trying  to add this line in my script - 

const ForwardEmail = require('forward-email');

I get - 
Cannot find module 'forward-email'

Looks like node installation problem. So I have tried the installation with other NPM packages, and they work fine. 
Any idea?

**Comment by joksnet** [comment]
I don't think the [published package](https://www.npmjs.com/package/forwardemail) is meant to be installed.

**Comment by niftylettuce** [comment]
Correct, we have not yet released a package to NPM yet.  Eventually there will be a CLI tool.

**Comment by niftylettuce** [comment]
`npm install https://github.com/niftylettuce/forward-email` in the meanwhile

**Comment by niftylettuce** [comment]
`forward-email` package available, see example implementation in `app.js` file and `ecosystem.json`
