### ISSUE TITLE
Privacy Issue

### ISSUE THREAD

**Issue by ashutoshpw** [forwardemail/free-email-forwarding#6]
Since TXT Records are public, the forwarding addresses will be always public. 
Is there any way to store the mapping in a private mapping?

**Comment by niftylettuce** [comment]
I'll implement something to resolve this, definitely w/encryption or a hash, just need time.  Thanks

**Comment by absane** [comment]
Second this. The whole idea of using a forwarding service for many people is privacy. Disclosing the true e-mail address to anyone looking for it (to unmask the forwarder) defeats this whole purpose.

As a workaround until it's implemented, one can maybe create an e-mail account with a major provider to forward to the actual destination using their own internal forwarding system... Give out "A", which forwards to "B" that isn't tied to you in any obvious way, which then forwards to "C".

**Comment by wei** [comment]
GPG is quite easy to implement.

**Comment by mattheworiordan** [comment]
Closed my dupe #19, but relevant suggestions for reference:

> Ideas that may work:
> * Allow a public key to be specified in the TXT record, and a private key to be uploaded to your service.
> * Allow forwarding to be configured from your service (via a simple web UI) once the MX records are set up
> * Provide a simple online encryption tool that will take the configuration, encrypt it using your public key, and only you will have the private key to decrypt. This may in fact be the easiest as you can keep your system effectively stateless.

**Comment by mattheworiordan** [comment]
I was thinking about this a little more, specifically in regards to keeping things simple.

My thinking was that if one was able to place the forwarding rules themselves in a DNS record that was "secure" in that it's not guessable such as `[secure-HASH].mydomain.com`, then there would be no need to obfuscate the rules meaning maintainability of these rules for people using this service would be considerably improved.

The next question is how does `forward-email` then know which record to use in a way that doesn't allow a spammer to find that hashed DNS entry.  I've got a few ideas:

- OpenPGP encrypted public entry which only forward-email can decrypt
- forward-email can send a hash entry to `*@mydomain.com` if an email is sent to say get-domain-hash@forwardemail.net from any email, then send the hash entry.
- Provide a form that allows you to enter a domain name you want to calculate the hash. It in turn asks you to add a DNS entry to the domain that proves ownership, whilst in turn providing you with a link to later use (or immediately if DNS changes are immediate) to get the hash after proving ownership.  I think this is my favourite approach as it doesn't require any encryption for users, and also does not require you to already have the domain receiving email, and it is also stateless.

WDYT?

**Comment by wei** [comment]
I think the idea of this project is so users don't have to setup mailboxes with anyone. (2) will require them to do so (whois email maybe better, but it complicates things). 
(3) is a good idea but requires quite a bit of work. imo (1) is the easiest solution but OpenPGP encrypted string is quite long maybe using a different key-based solution will work better : D

**Comment by niftylettuce** [comment]
I have a solution I just need time to implement, hold tight folks!

**Comment by mattheworiordan** [comment]
> I have a solution I just need time to implement, hold tight folks!

I'm intrigued...  Shout if you think I can help.  Happy to write some code / suggest some ideas / review anything you do.

**Comment by soyuka** [comment]
Maybe that we can help you implement this if you give us some informations about how you want to process? Thanks!

**Comment by unomind** [comment]
Good idea

**Comment by niftylettuce** [comment]
Releasing this soon... just added a few more features in my latest commit

**Comment by canufrank** [comment]
excited to hear you are implementing this

**Comment by tkrunning** [comment]
It would be fantastic if there would be a way of adding forwarding rules via an API of sorts (similar to [ForwardMX](https://forwardmx.io/wiki/12-api_documentation), which is good except it's not that reliable and the guy never replies to support emails).

Looking forward to having this feature nonetheless!

**Comment by mariux** [comment]
> It would be fantastic if there would be a way of adding forwarding rules via an API of sorts (similar to [ForwardMX](https://forwardmx.io/wiki/12-api_documentation), which is good except it's not that reliable and the guy never replies to support emails).

API would be great. i cannot give full xs to DNS to someone who just needs to be able to add a new email address. Also thumbs up for privacy increase - looking forward to having this, too..

and yes, forwardmx is hell on earth... lost a lot of really important emails and just received some emails two weeks dalayed.. so looking for a new alternative or i just start my own service ;)

**Comment by aaronstuder** [comment]
Any updates?

**Comment by niftylettuce** [comment]
as soon I release stable v1.0.0 of Lad I should have this up for us

https://lad.js.org

a few more things on my TODO's but pretty much done with the legwork

**Comment by niftylettuce** [comment]
Hey just an update here everyone that's following this thread...

In an attempt to make SPF more lenient, I accidentally wrote a bug, however it's already been fixed and deployed.  I also added an extra "reverse SPF" lookup in <https://github.com/niftylettuce/forward-email/commit/27dbd81a320ca32b23d9e5314d0b98a387ec22f1>, which will prevent emails from companies like Amazon, Twitch, Google, etc. from having their emails go to the spam folder or not get delivered at all (see #101).

I have a bit more work to do on Lad, but I am nearing completion.  Fortunately I have some close friends that are helping me get to the finish line.

**Comment by qoomon** [comment]
Any updates?
BTW Thx for this outstanding free service.

**Comment by pbmolini** [comment]
Are there any updates on this issue? I would like to use my domain name for forwarding emails to other people but I don't want to publicly expose their email address.

**Comment by niftylettuce** [comment]
This feature is launching along with other awesome things on or before September 1st 👍 😄

**Comment by marcklingen** [comment]
Thanks for your continued work on this!

**Comment by ObserverOfTime** [comment]
It's September 5th now and there's no indication that this has been implemented.

**Comment by niftylettuce** [comment]
It will be implemented ASAP.  I am configuring a few servers and simultaneously launching https://cabinjs.com and https://lad.js.org.  Will post back when ready.

**Comment by niftylettuce** [comment]
Again, sorry for the delay, going as fast I can with a day job as well to do.

**Comment by ObserverOfTime** [comment]
The delay is understandable. I never manage to meet self-appointed deadlines either. Just wanted to confirm that it hasn't been abandoned or anything.

**Comment by niftylettuce** [comment]
@ObserverOfTime This project is a main focus of mine and besides the obvious plans (e.g. features, global servers, load balancing, etc) - I plan to make this global and persist long beyond my existence through an organization.

**Comment by aaronstuder** [comment]
@niftylettuce thank you for all you do!

**Comment by allanlaal** [comment]
@niftylettuce can the same mechanism as #5 3f84c92 be used here to read the list of forwards from a local file?

I guess it could already be achieved by serving the same file on a local web server and denying public access to it (in the self hosted version)

**Comment by jjlin** [comment]
@niftylettuce While we wait for a more general solution, I'd like to propose a simple enhancement that would probably be all that's needed for a lot of people: there should be some special notation like `forward-email=@` that means "forward everything to the email address registered with the service".

**Comment by rEnr3n** [comment]
There is a similar service that does not need to expose email address on txt records. Users just needed to put create a txt record in this format `<sitename>,<username>`

E.g. `forwardemail,john`

All the forwarding rules are done inside the site's dashboard.

**Comment by niftylettuce** [comment]
Locking discussion because I am about to release this feature and sick of trolls.

**Comment by niftylettuce** [comment]
This feature is now available (FOR FREE) at https://forwardein beta program (ignore the pricing, as it's free for the beta program, then after beta program is over, you will have 30 days to enter billing info).

You can easily import existing TXT records with 1-click using the "Import TXT" button in the Alias Manager.

Try it out! https://forwardemail.net/features

Feedback is welcome.

🎉
