### ISSUE TITLE
mx2.forwardemail.net missing in SSL cert

### ISSUE THREAD

**Issue by niftylettuce** [forwardemail/free-email-forwarding#94]

**Comment by emilstahl** [comment]
Plans to fix this? Makes it hard to deploy MTA-STS:
```
Failure: Name in cert doesn't match hostname: x509: certificate is valid for mx1.forwardemail.net, www.mx1.forwardemail.net, not mx2.forwardemail.net

Error: hostname 'mx2.forwardemail.net' doesn't match either of 'mx1.forwardemail.net', 'www.mx1.forwardemail.net' ```

**Comment by emilstahl** [comment]
And you can't even just remove the mx2 MX record as you seems to be validating this:
`550 hej@emil.one is missing required DNS MX records of mx1.forwardemail.net, mx2.forwardemail.net`

And thanks for a great service!

**Comment by niftylettuce** [comment]
Will try to fix as soon I can

**Comment by niftylettuce** [comment]
This is resolved already btw
